## 1. Imports & Configuration

In [ ]:
import os, json, pickle, time, warnings, re, requests
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch, torch.nn as nn
from transformers import BertTokenizer, BertModel

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams.update({'figure.dpi': 120, 'figure.facecolor': 'white'})

PROJECT_ROOT    = Path(os.getcwd()).parent
DATA_DIR        = PROJECT_ROOT / 'data'
RESULTS_DIR     = PROJECT_ROOT / 'results'
MODELS_DIR      = PROJECT_ROOT / 'models'

STARPEP_CSV     = DATA_DIR / 'StarPep_APD_only.csv'
PREDICTIONS_CSV = RESULTS_DIR / 'test_predictions.csv'
EMBEDDINGS_NPY  = DATA_DIR / 'starpep_embeddings_cosine.npy'
METADATA_PKL    = DATA_DIR / 'starpep_metadata.pkl'
OUTPUT_CSV      = RESULTS_DIR / 'amp_rag_results.csv'

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO'] = '0.0'

PROTBERT_ID = 'Rostlab/prot_bert_bfd'
MAX_LEN     = 128
EMBED_BATCH = 16
TOP_K       = 3

OLLAMA_BASE_URL = 'http://localhost:11434'
OLLAMA_MODEL    = 'mistral:7b-instruct'
LLM_TEMPERATURE = 0
LLM_MAX_TOKENS  = 800

if torch.cuda.is_available():           DEVICE = 'cuda'
elif torch.backends.mps.is_available(): DEVICE = 'mps'
else:                                   DEVICE = 'cpu'

def clear_memory():
    if DEVICE == 'mps':  torch.mps.empty_cache()
    elif DEVICE == 'cuda': torch.cuda.empty_cache()

print(f'Device     : {DEVICE}')
print(f'Output CSV : {OUTPUT_CSV.name}')
print(f'LLM        : {OLLAMA_MODEL}  @ {OLLAMA_BASE_URL}')
print(f'Temperature: {LLM_TEMPERATURE}  (deterministic)')
print(f'Similarity : cosine (L2-normalised dot product, magnitude-invariant)')

/Users/deepugeorgejacob/Projects/amp-rag/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Device     : mps
Output CSV : amp_rag_results.csv
LLM        : mistral:7b-instruct  @ http://localhost:11434
Temperature: 0  (deterministic)
Similarity : cosine (L2-normalised dot product, magnitude-invariant)

## 1b. Ollama Health Check

Verifies that Ollama is running locally and `mistral:7b-instruct` is available.  
Start Ollama with: `ollama serve` (or open the Ollama desktop app).

In [ ]:
def ollama_health_check(base_url: str, model: str) -> bool:
    """Return True if Ollama is running and the model is available."""
    try:
        # Check server is up
        r = requests.get(f"{base_url}/api/tags", timeout=5)
        r.raise_for_status()
        models_available = [m["name"] for m in r.json().get("models", [])]
        print(f"Ollama server   : ✅ running")
        print(f"Models loaded   : {models_available}")

        if model in models_available:
            print(f"Target model    : ✅ {model} ready")
            return True
        else:
            print(f"Target model    : ❌ '{model}' not found")
            print(f"  Run: ollama pull {model}")
            return False

    except requests.exceptions.ConnectionError:
        print("❌ Ollama not reachable — start it with: ollama serve")
        return False
    except Exception as e:
        print(f"❌ Health check failed: {e}")
        return False

OLLAMA_READY = ollama_health_check(OLLAMA_BASE_URL, OLLAMA_MODEL)

if OLLAMA_READY:
    # Quick warm-up call to load model weights into memory
    print("\nWarm-up call (loads model weights)...")
    r = requests.post(
        f"{OLLAMA_BASE_URL}/api/chat",
        json={
            "model":    OLLAMA_MODEL,
            "messages": [{"role": "user", "content": "What is an antimicrobial peptide? One sentence."}],
            "stream":   False,
            "options":  {"temperature": LLM_TEMPERATURE, "num_predict": 60},
        },
        timeout=120,
    )
    warmup_reply = r.json()["message"]["content"].strip()
    print(f"✅ Model warm-up OK: {warmup_reply[:120]}")
else:
    print("\n⚠️  Fix Ollama before running Section 6.")

Ollama server   : ✅ running
Models loaded   : ['mistral:7b-instruct']
Target model    : ✅ mistral:7b-instruct ready

Warm-up call (loads model weights)...
✅ Model warm-up OK: Antimicrobial peptides are small, naturally occurring proteins that possess the ability to destroy microorganisms such a

In [ ]:
starpep_df = pd.read_csv(STARPEP_CSV)

starpep_df["sequence"] = starpep_df["sequence"].astype(str).str.strip().str.upper()
starpep_df = starpep_df[starpep_df["sequence"].str.len() > 0].reset_index(drop=True)

meta_cols = ["assessedAgainst", "relatedTo", "producedBy", "modifiedBy",
             "compiledIn", "linkedTo", "constitutedBy"]
for col in meta_cols:
    if col in starpep_df.columns:
        starpep_df[col] = starpep_df[col].fillna("").astype(str)

print(f"StarPep records     : {len(starpep_df):,}")
print(f"Columns             : {starpep_df.columns.tolist()}")
print(f"\nSequence length stats:")
print(starpep_df["length"].describe().round(1))
starpep_df.head(3)

StarPep records     : 2,949
Columns             : ['id', 'sequence', 'length', 'assessedAgainst', 'compiledIn', 'constitutedBy', 'linkedTo', 'modifiedBy', 'producedBy', 'relatedTo']

Sequence length stats:
count    2949.0
mean       30.8
std        16.4
min         2.0
25%        20.0
50%        28.0
75%        38.0
max       100.0
Name: length, dtype: float64

,id,sequence,length,assessedAgainst,compiledIn,constitutedBy,linkedTo,modifiedBy,producedBy,relatedTo
0,starPep_00000,GIGAVLKVLTTGLPALISWIKRKRQQ,26,HIV|Xanthomonas oryzae|Propionibacterium acnes...,HIPdb|ADAM|DRAMP_Patent|StraPep|AntiTbPdb|RAPD...,P at position 14 is D Proline|V at position 8 ...,PubMed: 23150226|PubMed: 10217411|PubMed: 2389...,Amidation|Lac=P-Amidophenyl-Β-D-Lactopyranosid...,Insecta|Apis cerana|Polistes|Apis mellifera|Sy...,Antifungal|Antibacterial|Antibiofilm|Toxic|Ant...
1,starPep_00001,GIGKFLHSAKKFGKAFVGEIMNS,23,Leukemia cancer|Serratia marcescens|Enterococc...,AMSDb|SATPdb|ADAM|AntiTbPdb|LAMP_Experimental|...,E at position 19 is D Glutamic Acid|K at posit...,PubMed: 9090128|DOI: 10.1093/jac/dkl120|PubMed...,Amidation,Synthetic construct|Xenopus ruwenzoriensis|Amp...,Toxic to mammals|Antiparasitic|Antibacterial|A...
2,starPep_00002,ILPWKWPWWPWRR,13,Streptococcus pyogenes|Sheep erythrocytes|Micr...,HIPdb|StraPep|AMSDb|CAMP_Validated|CAMP_Patent...,I at position 1 is D Isoleucine|W at position ...,PubMed: 11061996|PubMed: 16998183|PubMed: 1092...,Amidation|Acetylation,Bos taurus|Streptococcus equi|Synthetic construct,Surface-immobilization|Antibiofilm|Antileishma...

In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    PROTBERT_ID, do_lower_case=False, cache_dir=str(MODELS_DIR)
)
encoder = BertModel.from_pretrained(PROTBERT_ID, cache_dir=str(MODELS_DIR))
encoder = encoder.to(DEVICE)
encoder.eval()

total_params = sum(p.numel() for p in encoder.parameters())
print(f"✅ ProtBERT-BFD loaded  ({total_params/1e6:.0f}M params, device={DEVICE})")

✅ ProtBERT-BFD loaded  (420M params, device=mps)

In [ ]:
@torch.no_grad()
def embed_sequences(sequences: list[str],
                    tokenizer,
                    model,
                    device: str,
                    batch_size: int = EMBED_BATCH,
                    max_len: int = MAX_LEN) -> np.ndarray:
    """
    Embed a list of amino-acid sequences using ProtBERT-BFD.
    Returns a (N, 1024) float32 numpy array of [CLS] embeddings.
    """
    all_embeddings = []
    n_batches = (len(sequences) + batch_size - 1) // batch_size

    for i in range(0, len(sequences), batch_size):
        batch = sequences[i : i + batch_size]
        batch_num = i // batch_size + 1

        spaced = [" ".join(list(seq.upper().replace(" ", ""))) for seq in batch]

        enc = tokenizer(
            spaced,
            max_length=max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        input_ids = enc["input_ids"].to(device)
        attn_mask = enc["attention_mask"].to(device)

        out = model(input_ids=input_ids, attention_mask=attn_mask)
        cls_emb = out.last_hidden_state[:, 0, :].cpu().float().numpy()
        all_embeddings.append(cls_emb)

        del input_ids, attn_mask, out
        clear_memory()

        if batch_num % 20 == 0 or batch_num == n_batches:
            pct = batch_num / n_batches * 100
            print(f"  [{batch_num:4d}/{n_batches}]  {pct:5.1f}%  "
                  f"processed {min(i+batch_size, len(sequences)):4d}/{len(sequences)} seqs",
                  flush=True)

    return np.vstack(all_embeddings)   # (N, 1024)


print("Embedding function defined.")

Embedding function defined.

In [ ]:
if EMBEDDINGS_NPY.exists() and METADATA_PKL.exists():
    print('Cached embeddings found — loading...')
    store_embeddings = np.load(EMBEDDINGS_NPY)
    with open(METADATA_PKL, 'rb') as f:
        store_metadata = pickle.load(f)
    print(f'   Shape : {store_embeddings.shape}  (L2-normalised unit vectors)')
    print(f'   Meta  : {len(store_metadata)} records')
else:
    print(f'Embedding {len(starpep_df):,} StarPep sequences...')
    t0 = time.time()
    raw_embeddings = embed_sequences(starpep_df['sequence'].tolist(),
                                     tokenizer, encoder, DEVICE)

    norms = np.linalg.norm(raw_embeddings, axis=1, keepdims=True)
    store_embeddings = raw_embeddings / np.clip(norms, 1e-9, None)
    np.save(EMBEDDINGS_NPY, store_embeddings)
    print(f'\nL2-normalised embeddings saved -> {EMBEDDINGS_NPY.name}  {store_embeddings.shape}')

    store_metadata = []
    for _, row in starpep_df.iterrows():
        store_metadata.append({
            'id':              row['id'],
            'sequence':        row['sequence'],
            'length':          row.get('length', len(row['sequence'])),
            'assessedAgainst': row.get('assessedAgainst', ''),
            'relatedTo':       row.get('relatedTo', ''),
            'producedBy':      row.get('producedBy', ''),
            'modifiedBy':      row.get('modifiedBy', ''),
            'compiledIn':      row.get('compiledIn', ''),
            'linkedTo':        row.get('linkedTo', ''),
        })
    with open(METADATA_PKL, 'wb') as f:
        pickle.dump(store_metadata, f)
    print(f'Metadata saved -> {METADATA_PKL.name}  ({len(store_metadata)} records)')
    print(f'Time : {(time.time()-t0)/60:.1f} min')

sample_norms = np.linalg.norm(store_embeddings[:5], axis=1)
print(f'\nSample L2 norms (should be 1.0): {sample_norms.round(6)}')
print(f'Vector store ready — {store_embeddings.shape[0]:,} unit-norm AMPs @ {store_embeddings.shape[1]}-d')
print('Similarity: cosine  (store @ query.T  since both are unit vectors)')

Cached embeddings found — loading...
   Shape : (2949, 1024)  (L2-normalised unit vectors)
   Meta  : 2949 records

Sample L2 norms (should be 1.0): [1. 1. 1. 1. 1.]
Vector store ready — 2,949 unit-norm AMPs @ 1024-d
Similarity: cosine  (store @ query.T  since both are unit vectors)

In [ ]:
pred_df = pd.read_csv(PREDICTIONS_CSV)
print(f"Total test predictions : {len(pred_df):,}")
print(f"Class distribution     : {pred_df['predicted'].value_counts().to_dict()}")

pos_df = pred_df[pred_df["predicted"] == 1].reset_index(drop=True)
print(f"\nPositive AMP predictions : {len(pos_df):,}")
print(f"  True Positives (TP)    : {(pos_df['result']=='TP').sum()}")
print(f"  False Positives (FP)   : {(pos_df['result']=='FP').sum()}")
pos_df.head(5)

Total test predictions : 712
Class distribution     : {1: 358, 0: 354}

Positive AMP predictions : 358
  True Positives (TP)    : 323
  False Positives (FP)   : 35

               sequence  aa_length  label  prob_amp  predicted  correct result
0   GIVDFAKKVVGGIRNALGI         19      1  0.799875          1        1     TP
1         FISAIASMLGKFL         13      1  0.799397          1        1     TP
2         FLPLVGKILSGLI         13      1  0.798918          1        1     TP
3   GLLSALRKMIPHILSHIKK         19      1  0.800874          1        1     TP
4  AALKGCWTKSIPPKPCSGKR         20      1  0.799576          1        1     TP

In [ ]:
def retrieve_top_k(query_seq, store_embs, store_meta, tokenizer, model, device, top_k=TOP_K):
    query_emb = embed_sequences([query_seq], tokenizer, model, device, batch_size=1)
    query_unit = query_emb / np.clip(np.linalg.norm(query_emb), 1e-9, None)

    cosine_scores = (store_embs @ query_unit.T).squeeze()
    top_idx = np.argsort(cosine_scores)[::-1][:top_k]
    results = []
    for rank, idx in enumerate(top_idx, start=1):
        meta = dict(store_meta[idx])
        meta['rank']        = rank
        meta['cosine_sim']  = round(float(cosine_scores[idx]), 6)
        meta['is_self_match'] = (meta['cosine_sim'] >= 0.9999 and
                                  store_meta[idx]['sequence'].upper() == query_seq.upper())
        results.append(meta)
    return results

print('Retrieval function ready — cosine similarity, self-match included (score=1.0 flags known AMP).')

Retrieval function ready — cosine similarity, self-match included (score=1.0 flags known AMP).

In [ ]:
demo_seq = pos_df['sequence'].iloc[0]
print(f"Query : {demo_seq}  (len={len(demo_seq)} aa,  prob={pos_df['prob_amp'].iloc[0]:.4f})")
print('\nRetrieving top-3 via cosine similarity (self-match shown if present)...')
demo_results = retrieve_top_k(demo_seq, store_embeddings, store_metadata,
                               tokenizer, encoder, DEVICE)
print(f"\n{'Rank':<5} {'CosineSim':>10}  {'Self?':>5}  {'ID':<18} {'Seq':<30} {'Activities (first 3)'}")
print('-' * 115)
for r in demo_results:
    acts = ', '.join(r['relatedTo'].split('|')[:3]) if r['relatedTo'] else 'N/A'
    flag = ' ✓ SELF' if r['is_self_match'] else ''
    print(f"#{r['rank']:<4} {r['cosine_sim']:>10.6f}  {'YES' if r['is_self_match'] else 'no':>5}  {r['id']:<18} {r['sequence'][:28]:<30} {acts}{flag}")
print()
self_match = next((r for r in demo_results if r['is_self_match']), None)
if self_match:
    print(f"✅ Exact self-match found at rank {self_match['rank']} — this sequence IS in StarPep APD (cosine=1.0)")
else:
    print('ℹ️  No exact self-match in top-3 — sequence is not in StarPep APD (or only partially similar)')

Query : GIVDFAKKVVGGIRNALGI  (len=19 aa,  prob=0.7999)

Retrieving top-3 via cosine similarity (self-match shown if present)...
  [   1/1]  100.0%  processed    1/1 seqs

Rank   CosineSim  Self?  ID                 Seq                            Activities (first 3)
-------------------------------------------------------------------------------------------------------------------
#1      1.000000    YES  starPep_00309      GIVDFAKKVVGGIRNALGI            Anti-Gram negative, Anti-Gram positive, Antimicrobial ✓ SELF
#2      0.990304     no  starPep_00302      GILDFAKTVVGGIRNALGI            Antimicrobial, Anti-Gram positive, Anti-Gram negative
#3      0.979714     no  starPep_00295      GFVDLAKKVVGGIRNALGI            Antibacterial, Antimicrobial, Anti-Gram negative

✅ Exact self-match found at rank 1 — this sequence IS in StarPep APD (cosine=1.0)

In [ ]:
print(f"Retrieving top-{TOP_K} similar AMPs for {len(pos_df):,} positive predictions...")
print("(Each query embeds one sequence — may take a few minutes)\n")

retrieval_results = {}

for idx, row in pos_df.iterrows():
    seq = row["sequence"]
    hits = retrieve_top_k(seq, store_embeddings, store_metadata,
                          tokenizer, encoder, DEVICE)
    retrieval_results[seq] = {
        "sequence":  seq,
        "prob_amp":  row["prob_amp"],
        "true_label":int(row["label"]),
        "result":    row["result"],
        "hits":      hits,
    }
    if (idx + 1) % 50 == 0 or (idx + 1) == len(pos_df):
        print(f"  [{idx+1:>3}/{len(pos_df)}] done", flush=True)

clear_memory()
print(f"\n✅ Retrieval complete for {len(retrieval_results):,} sequences.")

Retrieving top-3 similar AMPs for 358 positive predictions...
(Each query embeds one sequence — may take a few minutes)

  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [ 50/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [100/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [150/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [200/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [250/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [300/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [350/358] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [358/358] done

✅ Retrieval complete for 358 sequences.

In [ ]:
HYDROPHOBIC = set("AVILMFYW")
CHARGED_POS = set("KRH")
CHARGED_NEG = set("DE")

def compute_properties(seq: str) -> dict:
    seq = seq.upper()
    n = len(seq)
    hydrophobic_count = sum(1 for aa in seq if aa in HYDROPHOBIC)
    pos_charge  = sum(1 for aa in seq if aa in CHARGED_POS)
    neg_charge  = sum(1 for aa in seq if aa in CHARGED_NEG)
    net_charge  = pos_charge - neg_charge
    return {
        "length":          n,
        "hydrophobicity":  round(hydrophobic_count / n * 100, 1),
        "net_charge":      net_charge,
        "pos_charged_pct": round(pos_charge / n * 100, 1),
        "neg_charged_pct": round(neg_charge / n * 100, 1),
    }


def format_activities(pipe_str: str, max_items: int = 6) -> str:
    items = [x.strip() for x in pipe_str.split("|") if x.strip()][:max_items]
    return ", ".join(items) if items else "Not specified"


def format_targets(pipe_str: str, max_items: int = 8) -> str:
    items = [x.strip() for x in pipe_str.split("|") if x.strip()][:max_items]
    return ", ".join(items) if items else "Not specified"


def build_prompt(query_seq: str,
                 prob_amp: float,
                 hits: list[dict]) -> str:
    """
    Construct an expert level biological prompt for the LLM.
    """
    props = compute_properties(query_seq)

    # Format the three retrieved AMPs
    hit_sections = []
    for h in hits:
        activities = format_activities(h.get("relatedTo", ""))
        targets    = format_targets(h.get("assessedAgainst", ""))
        source     = format_activities(h.get("producedBy", ""), max_items=3)
        mods       = format_activities(h.get("modifiedBy", ""), max_items=3)

        hit_sections.append(
            f"  [{h['rank']}] ID: {h['id']}  Similarity: {h['cosine_sim']:.4f}\n"
            f"      Sequence     : {h['sequence']}  (length: {h.get('length', len(h['sequence']))} aa)\n"
            f"      Activities   : {activities}\n"
            f"      Target organisms: {targets}\n"
            f"      Biological source: {source}\n"
            f"      Modifications : {mods if mods != 'Not specified' else 'None reported'}"
        )

    hits_text = "\n\n".join(hit_sections)

    prompt = f"""You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be an antimicrobial peptide with probability {prob_amp:.4f}:

QUERY SEQUENCE: {query_seq}

PHYSICOCHEMICAL PROPERTIES:
  • Length         : {props['length']} amino acids
  • Hydrophobicity : {props['hydrophobicity']}% hydrophobic residues ({', '.join(HYDROPHOBIC & set(query_seq.upper()))})
  • Net charge     : {props['net_charge']:+d} (Positive residues: {props['pos_charged_pct']}%, Negative: {props['neg_charged_pct']}%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BFD embedding space):

{hits_text}

Based on the query sequence and its closest known AMP neighbours, provide a comprehensive biological explanation covering:

1. ANTIMICROBIAL MECHANISM — What membrane-disrupting or intracellular mechanisms are most likely? Relate to physicochemical properties (charge, hydrophobicity, amphipathicity).
2. PREDICTED TARGET SPECTRUM — Which organisms or pathogens is this peptide most likely active against, based on the neighbours' target profiles?
3. STRUCTURAL FEATURES — What structural motifs (alpha-helix, beta-sheet, random coil) and key residues likely drive activity?
4. BIOLOGICAL ORIGIN & EVOLUTION — What biological context might this peptide arise from, based on the source organisms of similar peptides?
5. THERAPEUTIC POTENTIAL — What biomedical applications (antibacterial, antifungal, antiviral, anticancer) are most supported by the evidence?
6. RESEARCH RECOMMENDATIONS — What experimental assays would you recommend to validate this peptide's activity?

Be specific, cite amino acid positions where relevant, and ground your explanation in the retrieved AMP data."""

    return prompt


print("Prompt builder defined.")
print("\nSample prompt for demo sequence:")
print("-"*60)
sample_prompt = build_prompt(
    demo_seq, pos_df['prob_amp'].iloc[0], demo_results
)
print(sample_prompt[:600], "...")

Prompt builder defined.

Sample prompt for demo sequence:
------------------------------------------------------------
You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be an antimicrobial peptide with probability 0.7999:

QUERY SEQUENCE: GIVDFAKKVVGGIRNALGI

PHYSICOCHEMICAL PROPERTIES:
  • Length         : 19 amino acids
  • Hydrophobicity : 52.6% hydrophobic residues (A, V, F, L, I)
  • Net charge     : +2 (Positive residues: 15.8%, Negative: 5.3%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BFD embed ...

In [ ]:
print(sample_prompt)

You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be an antimicrobial peptide with probability 0.7999:

QUERY SEQUENCE: GIVDFAKKVVGGIRNALGI

PHYSICOCHEMICAL PROPERTIES:
  • Length         : 19 amino acids
  • Hydrophobicity : 52.6% hydrophobic residues (A, V, F, L, I)
  • Net charge     : +2 (Positive residues: 15.8%, Negative: 5.3%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BFD embedding space):

  [1] ID: starPep_00309  Similarity: 1.0000
      Sequence     : GIVDFAKKVVGGIRNALGI  (length: 19 aa)
      Activities   : Anti-Gram negative, Anti-Gram positive, Antimicrobial, Antibacterial
      Target organisms: Streptococcus uberis, Leuconostoc mesenteroides, Micrococcus luteus
      Biological source: Uperoleia inundata
      Modifications : Amidation

  [2] ID: starPep_00302  Similarity: 0.9903
      Sequence     : GILDFAKTVVGGIRNALGI  (length: 19 aa)
      Activities   : Antimicrobial, Anti-Gram positive, Anti-Gram negative, Antibacterial
      Target organisms: Leuconostoc mesenteroides, Streptococcus uberis, Staphylococcus aureus, Listeria innocua, Micrococcus luteus, Bacillus cereus, Escherichia coli
      Biological source: Uperoleia inundata
      Modifications : None reported

  [3] ID: starPep_00295  Similarity: 0.9797
      Sequence     : GFVDLAKKVVGGIRNALGI  (length: 19 aa)
      Activities   : Antibacterial, Antimicrobial, Anti-Gram negative, Anti-Gram positive
      Target organisms: Streptococcus uberis, Leuconostoc mesenteroides, Staphylococcus aureus, Listeria innocua, Bacillus cereus, Escherichia coli, Micrococcus luteus
      Biological source: Uperoleia inundata
      Modifications : None reported

Based on the query sequence and its closest known AMP neighbours, provide a comprehensive biological explanation covering:

1. ANTIMICROBIAL MECHANISM — What membrane-disrupting or intracellular mechanisms are most likely? Relate to physicochemical properties (charge, hydrophobicity, amphipathicity).
2. PREDICTED TARGET SPECTRUM — Which organisms or pathogens is this peptide most likely active against, based on the neighbours' target profiles?
3. STRUCTURAL FEATURES — What structural motifs (alpha-helix, beta-sheet, random coil) and key residues likely drive activity?
4. BIOLOGICAL ORIGIN & EVOLUTION — What biological context might this peptide arise from, based on the source organisms of similar peptides?
5. THERAPEUTIC POTENTIAL — What biomedical applications (antibacterial, antifungal, antiviral, anticancer) are most supported by the evidence?
6. RESEARCH RECOMMENDATIONS — What experimental assays would you recommend to validate this peptide's activity?

Be specific, cite amino acid positions where relevant, and ground your explanation in the retrieved AMP data.

In [ ]:
# ── Ollama LLM inference (local, temperature=0 → deterministic) ────────────────
def query_llm(prompt: str,
              model:  str    = OLLAMA_MODEL,
              base_url: str  = OLLAMA_BASE_URL,
              max_tokens: int = LLM_MAX_TOKENS,
              temperature: float = LLM_TEMPERATURE,
              retries: int = 3) -> str:
    """
    Send a chat prompt to the local Ollama instance.
    temperature=0 → greedy decoding → fully deterministic output.
    Returns the generated explanation text.
    """
    payload = {
        "model":  model,
        "stream": False,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an expert computational biologist specialising in "
                    "antimicrobial peptides (AMPs). Provide detailed, scientifically "
                    "accurate biological explanations using structured headings. "
                    "Base your answer strictly on the provided sequence data and "
                    "retrieved similar AMPs."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "options": {
            "temperature": temperature,
            "num_predict": max_tokens,
            "top_p":       1.0,
            "top_k":       1,
        },
    }

    for attempt in range(1, retries + 1):
        try:
            resp = requests.post(
                f"{base_url}/api/chat",
                json=payload,
                timeout=300,
            )
            resp.raise_for_status()
            return resp.json()["message"]["content"].strip()
        except requests.exceptions.Timeout:
            print(f"  ⚠️  Timeout on attempt {attempt}/{retries}. Retrying...")
        except requests.exceptions.ConnectionError:
            print(f"  ❌ Ollama not reachable. Is 'ollama serve' running?")
            return "[LLM ERROR] Ollama not reachable."
        except Exception as e:
            wait = 2 ** attempt
            print(f"  ⚠️  Attempt {attempt}/{retries} failed: {e}. Retrying in {wait}s...")
            time.sleep(wait)

    return f"[LLM ERROR] Could not generate explanation after {retries} attempts."


print(f"✅ Ollama LLM function ready")
print(f"   Model       : {OLLAMA_MODEL}")
print(f"   Temperature : {LLM_TEMPERATURE}  (greedy / deterministic)")
print(f"   top_k       : 1  (greedy decoding)")
print(f"   Max tokens  : {LLM_MAX_TOKENS}")

✅ Ollama LLM function ready
   Model       : mistral:7b-instruct
   Temperature : 0  (greedy / deterministic)
   top_k       : 1  (greedy decoding)
   Max tokens  : 800

### Generate explanations for all positive AMP predictions

In [ ]:
if not OLLAMA_READY:
    raise RuntimeError("Ollama is not running. Start it with: ollama serve")

print(f"Generating biological explanations for {len(retrieval_results):,} sequences...")
print(f"LLM   : {OLLAMA_MODEL}  (local Ollama)")
print(f"Temp  : {LLM_TEMPERATURE}  — deterministic greedy decoding\n")

explanations = {}
failed_seqs  = []
t_start = time.time()

for i, (seq, data) in enumerate(list(retrieval_results.items()), start=1):
    t0          = time.time()
    prompt      = build_prompt(seq, data["prob_amp"], data["hits"])
    explanation = query_llm(prompt)
    elapsed_seq = time.time() - t0

    explanations[seq] = explanation

    status = "✅" if "[LLM ERROR]" not in explanation else "❌"
    if "[LLM ERROR]" in explanation:
        failed_seqs.append(seq)

    print(f"  {status} [{i:>3}/{len(retrieval_results)}]  "
          f"{elapsed_seq:5.1f}s  seq={seq[:18]:<18}  "
          f"words={len(explanation.split()):>4}", flush=True)

total_elapsed = time.time() - t_start
print(f"\n{'─'*60}")
print(f"✅ Explanations generated : {len(explanations) - len(failed_seqs):,}")
print(f"❌ Failed                : {len(failed_seqs)}")
print(f"⏱  Total time            : {total_elapsed/60:.1f} min  "
      f"({total_elapsed/len(retrieval_results):.1f}s per sequence)")

Generating biological explanations for 358 sequences...
LLM   : mistral:7b-instruct  (local Ollama)
Temp  : 0  — deterministic greedy decoding

  ✅ [  1/358]   40.1s  seq=GIVDFAKKVVGGIRNALG  words= 413
  ✅ [  2/358]   33.0s  seq=FISAIASMLGKFL       words= 347
  ✅ [  3/358]   40.8s  seq=FLPLVGKILSGLI       words= 423
  ✅ [  4/358]   36.3s  seq=GLLSALRKMIPHILSHIK  words= 354
  ✅ [  5/358]   34.9s  seq=AALKGCWTKSIPPKPCSG  words= 365
  ✅ [  6/358]   41.5s  seq=YVPLPNVPQPGRRPFPTF  words= 418
  ✅ [  7/358]   41.5s  seq=FLPILAGLAAKLVPKVFC  words= 415
  ✅ [  8/358]   40.4s  seq=FLGGILNTITGLL       words= 457
  ✅ [  9/358]   41.5s  seq=GPVSAVLTELRCTCLRVT  words= 345
  ✅ [ 10/358]   41.2s  seq=FFRHLFRGAKAIFRGARQ  words= 409
  ✅ [ 11/358]   40.8s  seq=QNGGNQQGFGGEGIETFL  words= 445
  ✅ [ 12/358]   41.4s  seq=RSALSCQMCELVVKKYEG  words= 435
  ✅ [ 13/358]   41.0s  seq=ITSVSWCTPGCTSEGGGS  words= 450
  ✅ [ 14/358]   41.8s  seq=ELTEAQRRGLQVALEEFH  words= 421
  ✅ [ 15/358]   40.4s  seq=PPCRGIFCRRVGSSSAIA  words= 422
  ✅ [ 16/358]   41.0s  seq=RICRIIFLRVCR        words= 471
  ✅ [ 17/358]   41.8s  seq=RVKRFWPLVPVAINTVAA  words= 410
  ✅ [ 18/358]   41.4s  seq=GLWNSIKIAGKKLFVNVL  words= 424
  ✅ [ 19/358]   37.5s  seq=KRGLWESLKRKATKLGDD  words= 375
  ✅ [ 20/358]   40.7s  seq=FIGAVAGLLSKIF       words= 393
  ✅ [ 21/358]   39.9s  seq=GWINEEKIQKKIDERMGN  words= 414
  ✅ [ 22/358]   41.9s  seq=RLGDILQKAREKIEGGLK  words= 421
  ✅ [ 23/358]   38.4s  seq=FIGPVLKMATSILPTAIC  words= 385
  ✅ [ 24/358]   38.0s  seq=GFWTTAAEGLKKFAKAGL  words= 393
  ✅ [ 25/358]   41.2s  seq=CETPSKHFNGLCIRSSNC  words= 404
  ✅ [ 26/358]   39.7s  seq=VGRFRRLRKKTRKRLKKI  words= 398
  ✅ [ 27/358]   41.3s  seq=RCVCRRGVCRCVCTRGFC  words= 433
  ✅ [ 28/358]   37.0s  seq=FLPIIAGMAAKVICAITK  words= 370
  ✅ [ 29/358]   36.0s  seq=LRDLVCYCRARGCKGRER  words= 352
  ✅ [ 30/358]   39.2s  seq=FFGTALKIAANVLPTAIC  words= 396
  ✅ [ 31/358]   41.4s  seq=GIFSNMYARTPAGYFRGP  words= 439
  ✅ [ 32/358]   42.0s  seq=SAFTVWSGPGCNNRAERY  words= 432
  ✅ [ 33/358]   36.3s  seq=LFGLIPSLIGGLVSAFK   words= 358
  ✅ [ 34/358]   41.9s  seq=TNYGNGVGVPDAIMAGII  words= 436
  ✅ [ 35/358]   37.4s  seq=GLKDIFKAGLGSLVKGIA  words= 386
  ✅ [ 36/358]   41.0s  seq=PQRHPNTLSFRCSL      words= 409
  ✅ [ 37/358]   37.7s  seq=GIFSSRKCKTPSKTFKGI  words= 383
  ✅ [ 38/358]   41.9s  seq=GILDTIKSIASKVWNSKT  words= 412
  ✅ [ 39/358]   40.6s  seq=GLLGPLLKIAAKVGSNLL  words= 407
  ✅ [ 40/358]   41.5s  seq=GFTQGVRNSQSCRRNKGI  words= 422
  ✅ [ 41/358]   35.1s  seq=GIMDTIKNAAKDVVQSLL  words= 353
  ✅ [ 42/358]   41.6s  seq=GLGSLVGNALRIGAKLL   words= 443
  ✅ [ 43/358]   41.7s  seq=KRFKKFFKKLKNSVKKRA  words= 432
  ✅ [ 44/358]   40.4s  seq=SILSGNFGVGKKIVCGLS  words= 438
  ✅ [ 45/358]   41.3s  seq=FWGHIWNAVKRVGANALH  words= 412
  ✅ [ 46/358]   38.8s  seq=SSQEKSWLRANLMHQASQ  words= 405
  ✅ [ 47/358]   37.2s  seq=ASQPFQPQDHPSEAAALL  words= 365
  ✅ [ 48/358]   41.3s  seq=ATYYGNGLYCNKQKCWVD  words= 449
  ✅ [ 49/358]   41.7s  seq=ISQSDAILSAIWSGIKSL  words= 426
  ✅ [ 50/358]   41.4s  seq=LVQRGRFGRFLKKVRRFI  words= 419
  ✅ [ 51/358]   41.5s  seq=FIITGLVRGLTKLF      words= 428
  ✅ [ 52/358]   39.7s  seq=GLFSVLGSVAKHLLPHVV  words= 410
  ✅ [ 53/358]   42.0s  seq=SFGLCRLRRGFCARGRCR  words= 401
  ✅ [ 54/358]   41.8s  seq=NCCNNLHHDIERFKAIKA  words= 420
  ✅ [ 55/358]   40.6s  seq=RDEMALFLRLLDQVIFGF  words= 436
  ✅ [ 56/358]   40.9s  seq=GDAECASSTHTPTMSGCK  words= 437
  ✅ [ 57/358]   40.0s  seq=LVRGCWTKSYPPKPCFVR  words= 396
  ✅ [ 58/358]   41.1s  seq=FFPFLLGALGSLLPKIF   words= 429
  ✅ [ 59/358]   41.1s  seq=FFDEKCNKLKGTCKNNCG  words= 433
  ✅ [ 60/358]   36.4s  seq=GQTCLPMEEAFELPLDDC  words= 381
  ✅ [ 61/358]   41.1s  seq=FIGAIARLLSKIF       words= 418
  ✅ [ 62/358]   37.7s  seq=GLFDVIKKVASVIGGL    words= 393
  ✅ [ 63/358]   41.5s  seq=ILGEIWKGIKDIL       words= 408
  ✅ [ 64/358]   41.5s  seq=SNSSSSSTGSNTPLSTAP  words= 456
  ✅ [ 65/358]   41.2s  seq=DHKSCCPHHHYE        words= 433
  ✅ [ 66/358]   42.6s  seq=GILMDTFKGAAKNVAGFL  words= 448
  ✅ [ 67/358]   41.4s  seq=QLKVDLWGTRSGIQPEQH  words= 434
  ✅ [ 68/358]   41.9s  seq=RLASYSFRRVQ         words= 410
  ✅ [ 69/358]   41.2s  seq=GLLLDTVKGAAKNVAGIL  words= 428
  ✅ [ 70/358]   38.8s  seq=GGLKKLGKKLEGVGKRVF  words= 410
  ✅ [ 71/358]   41.1s  seq=KAAAAKKSPKKPKKPAAA  words= 448
  ✅ [ 72/358]   41.8s  seq=FTCNSYACKAHCILQGHK  words= 437
  ✅ [ 73/358]   38.4s  seq=GLWSKIKEVGKEAAKAAA  words= 406
  ✅ [ 74/358]   41.7s  seq=FIHHIIGGLFSVGKHIHS  words= 411
  ✅ [ 75/358]   36.8s  seq=FFPLALLCKVFKKC      words= 383
  ✅ [ 76/358]   37.2s  seq=AIFIFIRWLLKLGHHGRA  words= 384
  ✅ [ 77/358]   41.0s  seq=ILPIIGKILSTIF       words= 450
  ✅ [ 78/358]   42.4s  seq=SPRPDDKKNQGSASVDVQ  words= 419
  ✅ [ 79/358]   41.2s  seq=TTPLCVGVIIGITASIKI  words= 418
  ✅ [ 80/358]   42.0s  seq=ATCDLLSGFGVGDSACAA  words= 394
  ✅ [ 81/358]   35.9s  seq=RRLRPRHQHFPSERPWPK  words= 375
  ✅ [ 82/358]   42.2s  seq=KYYGNGLSCSKKGCTVNW  words= 417
  ✅ [ 83/358]   41.2s  seq=FIGALLGPLLNLLK      words= 430
  ✅ [ 84/358]   39.2s  seq=RLGTALPALLKTLLAGLN  words= 399
  ✅ [ 85/358]   41.8s  seq=SSFSPPRGPPGWGPPCVQ  words= 386
  ✅ [ 86/358]   39.3s  seq=LNLKGIFKKVASLLT     words= 391
  ✅ [ 87/358]   41.1s  seq=AVDFSSCARMDVPGLSKV  words= 417
  ✅ [ 88/358]   38.0s  seq=GTRCGETCFVLPCWSAKF  words= 401
  ✅ [ 89/358]   36.1s  seq=IDWKKLLDAAKQIL      words= 399
  ✅ [ 90/358]   39.1s  seq=INWKKIKSIIKAAMN     words= 421
  ✅ [ 91/358]   41.3s  seq=RRTCHCRSRCLRRESNSG  words= 425
  ✅ [ 92/358]   39.2s  seq=KAYSMPRCKYLFRAVLCW  words= 410
  ✅ [ 93/358]   41.3s  seq=GWFGKAFRSVSNFYKKHK  words= 421
  ✅ [ 94/358]   41.8s  seq=TNWKKIGKCYAGTLGSAV  words= 380
  ✅ [ 95/358]   41.3s  seq=CVISAGWNHKIRCKLTGN  words= 436
  ✅ [ 96/358]   40.9s  seq=ENFFKEIERAGQRIRDAI  words= 428
  ✅ [ 97/358]   41.4s  seq=MGAIAKLVAKFGWPIVKK  words= 432
  ✅ [ 98/358]   39.5s  seq=GLLNGLALRLGKRALKKI  words= 404
  ✅ [ 99/358]   46.8s  seq=GILLDKLKNFAKTAGKGV  words= 419
  ✅ [100/358]   44.8s  seq=TDTNVIGECFDEWSRCHR  words= 424
  ✅ [101/358]   45.3s  seq=GGLRSLGRKILRAWKKYG  words= 411
  ✅ [102/358]   45.3s  seq=QDKCKKVYENYPVSKCQL  words= 413
  ✅ [103/358]   43.9s  seq=GKWGWIYITILFADVGGF  words= 430
  ✅ [104/358]   44.6s  seq=SFLDTLKNLAISAAKGAG  words= 418
  ✅ [105/358]   38.9s  seq=CKQSCSFGPFTFVCDGNT  words= 408
  ✅ [106/358]   34.8s  seq=SLGVTLGAAGLYTATQTI  words= 360
  ✅ [107/358]   41.5s  seq=SAPRGCWTKSYPPKPCK   words= 410
  ✅ [108/358]   41.6s  seq=ILGPVLGLVSDTLDDVLG  words= 423
  ✅ [109/358]   43.1s  seq=ASGRDIAMAIGTLSGQFV  words= 424
  ✅ [110/358]   42.0s  seq=AYPGNGVHCGKYSCTVDK  words= 434
  ✅ [111/358]   41.1s  seq=IASKFICTPGCAKTGSFN  words= 449
  ✅ [112/358]   36.2s  seq=GWRLLLKKAEVKTVGKLA  words= 372
  ✅ [113/358]   39.5s  seq=ATNIPFKVHFRCKAAFC   words= 443
  ✅ [114/358]   41.3s  seq=ILGPVIKTIGGVIGGLLK  words= 429
  ✅ [115/358]   41.0s  seq=RWKPFKKELKVGRNIRDG  words= 418
  ✅ [116/358]   41.4s  seq=ATYDGKCYKKDNICKYKA  words= 463
  ✅ [117/358]   41.4s  seq=IFGAIWKGISSLL       words= 453
  ✅ [118/358]   41.9s  seq=SPIHACRYQRGVCIPGPC  words= 400
  ✅ [119/358]   41.2s  seq=FLPAIFRMAAKVVPTIIC  words= 431
  ✅ [120/358]   36.2s  seq=VGSRYLCTPGSCWKLVCF  words= 383
  ✅ [121/358]   42.2s  seq=SLFELGKMILQETGKNPA  words= 431
  ✅ [122/358]   39.7s  seq=INLKALAALAKKIL      words= 398
  ✅ [123/358]   40.2s  seq=TKCRTIASLLTAAPNPHS  words= 411
  ✅ [124/358]   42.3s  seq=TWLKKRRWKKAKPP      words= 417
  ✅ [125/358]   40.9s  seq=FQTSEAILPMASSCCTEV  words= 366
  ✅ [126/358]   41.7s  seq=ASFPWSCPSLSGVCRKVC  words= 419
  ✅ [127/358]   41.4s  seq=VTCDILSVEAKGVKLNDA  words= 414
  ✅ [128/358]   40.1s  seq=KTYYGTNGVHCTKKSLWG  words= 403
  ✅ [129/358]   40.8s  seq=GILDTLKEFGKTAAKGIA  words= 431
  ✅ [130/358]   41.2s  seq=GKCSVLKKVACAAAIAGA  words= 427
  ✅ [131/358]   41.0s  seq=SALVGCWTKSYPPNPCFG  words= 421
  ✅ [132/358]   41.0s  seq=FLNALKNFAKTAGKRLKS  words= 404
  ✅ [133/358]   38.8s  seq=ILPILSLIGGLLGK      words= 401
  ✅ [134/358]   41.1s  seq=FVPYNPPRPYQSKPFPSF  words= 448
  ✅ [135/358]   41.7s  seq=ILGTILGLLKGL        words= 383
  ✅ [136/358]   42.0s  seq=SRITRALVQIVKGLK     words= 408
  ✅ [137/358]   37.3s  seq=GFLDVVKHIGKAALGAVT  words= 384
  ✅ [138/358]   40.8s  seq=GIMDTIKDTAKTVAVGLL  words= 447
  ✅ [139/358]   41.1s  seq=FLPVLAGIAAKVVPALFC  words= 410
  ✅ [140/358]   37.9s  seq=LFKLLGKIIHHVGNFVHG  words= 381
  ✅ [141/358]   40.7s  seq=GFGSVLGKALKFGANLL   words= 381
  ✅ [142/358]   43.5s  seq=MNLNGLPASTNVIDLRGK  words= 443
  ✅ [143/358]   43.0s  seq=GWINEEKIQKKIDEKIGN  words= 410
  ✅ [144/358]   42.4s  seq=GIFSKFGGKAIKNLFIKG  words= 432
  ✅ [145/358]   42.9s  seq=GFFSTVKNLATNVAGTVI  words= 433
  ✅ [146/358]   37.7s  seq=FLPGLIKAAVGVGSTILC  words= 378
  ✅ [147/358]   42.9s  seq=DRCSQQCQHHRDPDRKQQ  words= 417
  ✅ [148/358]   42.3s  seq=QGHDVGFCCLGTTRGKAG  words= 409
  ✅ [149/358]   42.8s  seq=GTFIKQQRKQKQQRHHTS  words= 444
  ✅ [150/358]   39.9s  seq=GWKKWLRKGAKHLGQAAI  words= 427
  ✅ [151/358]   41.0s  seq=LCFLTLRHKRPKAKYIIW  words= 395
  ✅ [152/358]   36.7s  seq=IWLTALKFLGKHAAKHLA  words= 353
  ✅ [153/358]   43.0s  seq=ACIKNGGRCVASGGPPYC  words= 402
  ✅ [154/358]   43.2s  seq=LVATGMAAGVAKTIVNAV  words= 415
  ✅ [155/358]   42.9s  seq=VSFKECCEAKNYEGCVRC  words= 428
  ✅ [156/358]   44.7s  seq=GLVSSIGKALGGLLADVV  words= 422
  ✅ [157/358]   43.4s  seq=GLLDIVKKVVGAFGSL    words= 424
  ✅ [158/358]   42.3s  seq=GRCVCRKQLLCSYRERRI  words= 426
  ✅ [159/358]   42.4s  seq=KRRHWFPLSFQEFLEQLR  words= 437
  ✅ [160/358]   40.8s  seq=FLPVILPVIGKLLSGIL   words= 405
  ✅ [161/358]   41.0s  seq=FLPLLAGLAAKWF       words= 425
  ✅ [162/358]   39.2s  seq=VAPIAKYLATALAKWALK  words= 384
  ✅ [163/358]   40.9s  seq=GILDFAKTVVGGIRNALG  words= 412
  ✅ [164/358]   40.7s  seq=GIGGKILGGLRTALKGAA  words= 383
  ✅ [165/358]   39.7s  seq=TFNNISLLAQNSLEIISK  words= 405
  ✅ [166/358]   42.1s  seq=GILDSFKGVAKGVAKDLA  words= 429
  ✅ [167/358]   35.5s  seq=FFSLLPSLIGGLVSAIK   words= 354
  ✅ [168/358]   42.4s  seq=NRWGDTVLSAASGAGTGI  words= 412
  ✅ [169/358]   42.3s  seq=GLFDVIKKVASVIGLASP  words= 424
  ✅ [170/358]   40.9s  seq=GVLDILKNAAKNILAHAA  words= 437
  ✅ [171/358]   36.6s  seq=VGALAVVVWLWLWLW     words= 367
  ✅ [172/358]   41.9s  seq=FMGSALRIAAKVLPAALC  words= 402
  ✅ [173/358]   38.5s  seq=GFLGPLLKLGLKGVAKVL  words= 385
  ✅ [174/358]   41.8s  seq=KKLLKWLKKLL         words= 408
  ✅ [175/358]   39.6s  seq=SYVGDCGSNGGSCVSSYC  words= 393
  ✅ [176/358]   42.0s  seq=GLFSVVTGVLKAVGKNVA  words= 416
  ✅ [177/358]   37.3s  seq=FHTGHQDKVRCFFCYGGL  words= 383
  ✅ [178/358]   37.7s  seq=SSVVSYIAQTYSLLGKKA  words= 397
  ✅ [179/358]   41.9s  seq=GILDTLKNLAKTAGKGAL  words= 441
  ✅ [180/358]   42.1s  seq=SLWETIKNAGKGFILNIL  words= 425
  ✅ [181/358]   39.7s  seq=IFKAIWSGIKSLF       words= 409
  ✅ [182/358]   42.3s  seq=KYYGNGVTCGKHSCSVNW  words= 376
  ✅ [183/358]   42.3s  seq=IKGYTRCFAYANERQMPD  words= 393
  ✅ [184/358]   40.4s  seq=RFGRFLRKIRRFRPKVTI  words= 416
  ✅ [185/358]   40.8s  seq=FFGHLYRGITSVVKHVHG  words= 409
  ✅ [186/358]   37.6s  seq=KVPIGAIKKGGKIIKKGL  words= 417
  ✅ [187/358]   41.9s  seq=FIPLVSGLFSRLL       words= 427
  ✅ [188/358]   42.1s  seq=GILSNVLGMGKKIVCGLS  words= 436
  ✅ [189/358]   42.1s  seq=GLGGAKKNFIIAANKTAP  words= 453
  ✅ [190/358]   39.9s  seq=CVLIGQRCDNDRGPRCCS  words= 411
  ✅ [191/358]   40.8s  seq=GLWSKIKEAAKTAGLMAM  words= 423
  ✅ [192/358]   39.7s  seq=VNWKKILGKIIKVVK     words= 410
  ✅ [193/358]   38.1s  seq=FLSLIPHIVSGVAALAKH  words= 392
  ✅ [194/358]   40.1s  seq=FFHHIFRGIVHVGKTIHK  words= 398
  ✅ [195/358]   31.4s  seq=TGRIIYEACSCITTMLSR  words= 322
  ✅ [196/358]   41.5s  seq=VNYGNGVSCSKTKCSVNW  words= 425
  ✅ [197/358]   41.0s  seq=GPVGLLSSPGSLPPVGGA  words= 448
  ✅ [198/358]   41.5s  seq=KCNQLFELLQDLVDHVND  words= 410
  ✅ [199/358]   41.0s  seq=GKVWDWIKSTAKKLWNSE  words= 413
  ✅ [200/358]   41.5s  seq=IMKRHFTQALSTVTPRIP  words= 435
  ✅ [201/358]   37.5s  seq=LQDAALGWGRRCPRCPRC  words= 391
  ✅ [202/358]   36.1s  seq=YEALVTSILGKLTGLWHN  words= 375
  ✅ [203/358]   41.9s  seq=GLRKKFRKTRKRIQKLGR  words= 383
  ✅ [204/358]   35.4s  seq=ALKAALLAILKIVRVIKK  words= 372
  ✅ [205/358]   40.7s  seq=GTTVVNSTFSIVLGNKGY  words= 403
  ✅ [206/358]   35.8s  seq=GIFTKINKKKAKTGVFNI  words= 365
  ✅ [207/358]   40.5s  seq=GFRDVLKGAAKAFVKTVA  words= 458
  ✅ [208/358]   37.9s  seq=GWASKIGQTLGKIAKVGL  words= 379
  ✅ [209/358]   41.0s  seq=SWFSRTVHNVGNAVRKGI  words= 435
  ✅ [210/358]   41.2s  seq=KCKWWNISCDLGNNGHVC  words= 396
  ✅ [211/358]   40.8s  seq=FLGAIAAALPHVINAVTN  words= 451
  ✅ [212/358]   41.0s  seq=ANTLGSAAAQAVMQTA    words= 425
  ✅ [213/358]   41.1s  seq=NRLSCHRNKGVCVPSRCP  words= 419
  ✅ [214/358]   41.2s  seq=FPISPAISCASSCPS     words= 433
  ✅ [215/358]   39.1s  seq=GILGKLWEGFKSIV      words= 409
  ✅ [216/358]   37.8s  seq=GIPCGESCVWIPCISSAI  words= 384
  ✅ [217/358]   41.4s  seq=SLGNFFRKARKKIGEEFK  words= 434
  ✅ [218/358]   40.3s  seq=KSCCRNTWARNCYNVCRL  words= 428
  ✅ [219/358]   32.6s  seq=MNSSSVLFVCILGACSVW  words= 344
  ✅ [220/358]   41.1s  seq=RCVCRRGVCRCVCRRGVC  words= 424
  ✅ [221/358]   42.2s  seq=LLPIVGNLLKSLL       words= 422
  ✅ [222/358]   42.4s  seq=GIMDSVKGLAKNLAGKLL  words= 456
  ✅ [223/358]   38.3s  seq=FISQIISTAHI         words= 397
  ✅ [224/358]   37.9s  seq=FKTWKRPPFQTSCWGIIK  words= 377
  ✅ [225/358]   40.4s  seq=YQEPVLGPVRGPFPIIV   words= 417
  ✅ [226/358]   42.0s  seq=GLLSKVLGVGKKVLCGVS  words= 418
  ✅ [227/358]   42.1s  seq=FSTKTRNWFSEHFKKVKE  words= 429
  ✅ [228/358]   42.7s  seq=HSHACTSYWCGKFCGTAS  words= 413
  ✅ [229/358]   42.4s  seq=ARGTNVGRECCLEYFKGA  words= 468
  ✅ [230/358]   42.5s  seq=YDTGIQGWTCGSRGLCRK  words= 438
  ✅ [231/358]   41.5s  seq=KIKWFKTMKSIAKFIAKE  words= 409
  ✅ [232/358]   40.1s  seq=ATCDLLSMWNVNHSACAA  words= 419
  ✅ [233/358]   40.1s  seq=FLPVIAGLLSKLF       words= 394
  ✅ [234/358]   42.0s  seq=GIKDWIKGAAKKLIKTVA  words= 442
  ✅ [235/358]   36.5s  seq=GSGVIPTISHECHMNSFQ  words= 377
  ✅ [236/358]   40.5s  seq=SPAIWGCDSFLGYCRLAC  words= 414
  ✅ [237/358]   42.5s  seq=VGECVRGRCPSGMCCSQF  words= 413
  ✅ [238/358]   39.6s  seq=NIGLFTSTCFSSQCFSSK  words= 389
  ✅ [239/358]   41.1s  seq=PAAIKGAVAAGAGRLP    words= 397
  ✅ [240/358]   42.5s  seq=RISKKKGKGSWIKNGLIK  words= 395
  ✅ [241/358]   39.4s  seq=FMPILSCSRFKRC       words= 410
  ✅ [242/358]   42.2s  seq=LLTDFPEKFAERRHVFL   words= 432
  ✅ [243/358]   34.4s  seq=DCTRWIIGINGRICRD    words= 332
  ✅ [244/358]   42.4s  seq=DWTCWSCLVCAACSVELL  words= 390
  ✅ [245/358]   40.4s  seq=RCVCTRGFCRCVCTRGFC  words= 435
  ✅ [246/358]   42.5s  seq=RRWCFRVCYRGFCYRKCR  words= 416
  ✅ [247/358]   41.8s  seq=RFNIRAGFFWDGIDRSNG  words= 407
  ✅ [248/358]   42.3s  seq=GIGKFLHSAGKFGKAFIG  words= 395
  ✅ [249/358]   41.1s  seq=YRQSMNNFQGLRSFGCRF  words= 395
  ✅ [250/358]   40.7s  seq=VDKPPYLPRPPPPRRIYN  words= 416
  ✅ [251/358]   39.5s  seq=LFGSVKAWFKGAKKGFQD  words= 387
  ✅ [252/358]   38.4s  seq=GRKSDCFRKNGFCAFLKC  words= 385
  ✅ [253/358]   42.2s  seq=GLWNTIKEAGKKFAINVL  words= 411
  ✅ [254/358]   40.7s  seq=GLLDFVTGVGKDIFAQLI  words= 416
  ✅ [255/358]   37.8s  seq=GFGCPNDYSCSNHCRDSI  words= 378
  ✅ [256/358]   42.1s  seq=ALWKDILKNVGKAAGKAV  words= 439
  ✅ [257/358]   42.3s  seq=DQYKCLQHGGFCLRSSCP  words= 427
  ✅ [258/358]   41.3s  seq=FLKPLFNAALKLLP      words= 419
  ✅ [259/358]   39.2s  seq=FLPVLAGVLSRA        words= 376
  ✅ [260/358]   34.3s  seq=FLPLLLAGLPLKLCFLFK  words= 334
  ✅ [261/358]   41.5s  seq=INVLGILGLLGKALSHL   words= 442
  ✅ [262/358]   42.2s  seq=GIGDPVTCLKSGAICHPV  words= 425
  ✅ [263/358]   42.1s  seq=QRFSQPTFKLPQGRLTLS  words= 392
  ✅ [264/358]   39.7s  seq=SDCNINSNTAADVILCFN  words= 431
  ✅ [265/358]   42.0s  seq=GKREKCLRRNGFCAFLKC  words= 440
  ✅ [266/358]   39.7s  seq=MHDFWVLWVLLEYIYNSA  words= 404
  ✅ [267/358]   37.7s  seq=HHHHRFGKIGHELHKGVK  words= 387
  ✅ [268/358]   36.0s  seq=GFMSKVANFAKKFAKGGV  words= 356
  ✅ [269/358]   40.8s  seq=GICRCICTRGFCRCICVL  words= 434
  ✅ [270/358]   38.0s  seq=SPKKTKPVKPKKVA      words= 392
  ✅ [271/358]   42.2s  seq=NPVSCVRNKGICVPIRCP  words= 409
  ✅ [272/358]   41.5s  seq=GGGVIQTISHECRMNSWQ  words= 415
  ✅ [273/358]   41.8s  seq=GLLASLGKVFGGYLAEKL  words= 433
  ✅ [274/358]   41.7s  seq=GKNGVFKTISHECHLNTW  words= 474
  ✅ [275/358]   42.4s  seq=APGNKAECEREKGYCGFL  words= 411
  ✅ [276/358]   42.9s  seq=RVPPYLGRDCKHWCRDNN  words= 422
  ✅ [277/358]   41.8s  seq=RVKRVWPLVIRTVIAGYN  words= 425
  ✅ [278/358]   41.9s  seq=KSIGPTCPFAGSCEVS    words= 404
  ✅ [279/358]   43.0s  seq=MDVFMKGLSKAKEGVVAA  words= 382
  ✅ [280/358]   39.5s  seq=GILSLFTGGIKALGKTLF  words= 398
  ✅ [281/358]   42.5s  seq=RWKIFKKIEKVGRNVRDG  words= 418
  ✅ [282/358]   36.2s  seq=GFVDFLKKVAGTIANVVT  words= 322
  ✅ [283/358]   42.3s  seq=GIGKFLHSAKKFGKAFVG  words= 409
  ✅ [284/358]   37.2s  seq=GMASKAGSVLGKITKIAL  words= 364
  ✅ [285/358]   42.1s  seq=ILPFVAGVAAMEMEHVYC  words= 449
  ✅ [286/358]   42.0s  seq=GPASVPTTCCFNLANRKI  words= 402
  ✅ [287/358]   42.7s  seq=GVWDWLKKTAKNVWNSDI  words= 420
  ✅ [288/358]   38.4s  seq=INLLKIAKGIIKSL      words= 385
  ✅ [289/358]   41.9s  seq=MTPFWRGVSLRPIGASCR  words= 423
  ✅ [290/358]   39.2s  seq=GVGSFIHKVVSAIKNVA   words= 381
  ✅ [291/358]   42.7s  seq=GLMSLFKGVLKTAGKHIF  words= 430
  ✅ [292/358]   40.9s  seq=INWLKLGKMVIDAL      words= 416
  ✅ [293/358]   42.3s  seq=KQEGRDHDKSKGHFHMIV  words= 416
  ✅ [294/358]   42.1s  seq=GILSLVKGVAKLAGKGLA  words= 444
  ✅ [295/358]   35.4s  seq=QQCGRQASGRLCGNRLCC  words= 338
  ✅ [296/358]   37.9s  seq=NVTPATKPTPSKPGYCRV  words= 367
  ✅ [297/358]   42.9s  seq=NKGCATCSIGAACLVDGP  words= 394
  ✅ [298/358]   39.8s  seq=GCFEDWSRCSPSTSRGTG  words= 385
  ✅ [299/358]   41.5s  seq=VDKPDYRPRPRPPNM     words= 439
  ✅ [300/358]   42.0s  seq=IIGPVLGMVGSALGGLLK  words= 421
  ✅ [301/358]   38.3s  seq=GTMLFTNPLIQRTPLAFK  words= 344
  ✅ [302/358]   38.5s  seq=GWASSIGSILGKFAKGGA  words= 346
  ✅ [303/358]   40.1s  seq=GILDAIKAIAKAAG      words= 394
  ✅ [304/358]   41.7s  seq=GFLSALKKYLPIVLKHV   words= 426
  ✅ [305/358]   41.9s  seq=IFGAIAGLLKNIF       words= 434
  ✅ [306/358]   40.2s  seq=FYCKGTNKRMRDLARWPM  words= 430
  ✅ [307/358]   40.8s  seq=GEPMPGDDDEDIVMTSTQ  words= 404
  ✅ [308/358]   38.6s  seq=FIKWKFRWWKWRK       words= 416
  ✅ [309/358]   40.1s  seq=FMPIIGRLMSGSL       words= 386
  ✅ [310/358]   38.1s  seq=IKIPAVVKDTLKKVAKGV  words= 384
  ✅ [311/358]   41.8s  seq=LIQRGRFGRFLGRIRRFR  words= 431
  ✅ [312/358]   40.8s  seq=RESPSSRMECYEQAERYG  words= 405
  ✅ [313/358]   41.5s  seq=KFFRKLKKSVKKRAKEFF  words= 426
  ✅ [314/358]   41.0s  seq=GFWGSLWEGVKSVV      words= 423
  ✅ [315/358]   39.2s  seq=MPYSGLFMPLGGWI      words= 409
  ✅ [316/358]   34.8s  seq=FIGALLRPALKLLAGK    words= 353
  ✅ [317/358]   41.2s  seq=GFLGPLLKLAAKGVAKVI  words= 453
  ✅ [318/358]   40.1s  seq=MAGFLKVVQLLAKYGSKA  words= 410
  ✅ [319/358]   37.8s  seq=ATYYGNGLYCNKEKCWVD  words= 388
  ✅ [320/358]   40.3s  seq=FFRLLFHGVHHVGKIKPR  words= 413
  ✅ [321/358]   38.5s  seq=FITLLLRKFICSITKKC   words= 396
  ✅ [322/358]   36.7s  seq=GLWSTIKNVGKEAAIAAG  words= 396
  ✅ [323/358]   40.9s  seq=GKYGPGSLVCK         words= 415
  ✅ [324/358]   41.2s  seq=VPTRHARPRPQPRPRPGT  words= 385
  ✅ [325/358]   41.2s  seq=SGEKKCWNRSGHCRKQCK  words= 376
  ✅ [326/358]   38.5s  seq=DQLIQHELEKKLNWDDV   words= 419
  ✅ [327/358]   41.4s  seq=RHCLSQSHRFKGMCVSSN  words= 424
  ✅ [328/358]   39.1s  seq=VSCGDVTSSIAPCLSYVM  words= 408
  ✅ [329/358]   31.6s  seq=FLFPLITSFLSKVL      words= 332
  ✅ [330/358]   38.2s  seq=RRICRCRIGRCLGLEVYF  words= 402
  ✅ [331/358]   39.6s  seq=QPKGLSRAHWFEIQHIQT  words= 380
  ✅ [332/358]   37.2s  seq=SSLLEKGLDGAKKAVGGL  words= 389
  ✅ [333/358]   36.4s  seq=ILPFVAGVAAEMMQHVYC  words= 359
  ✅ [334/358]   41.0s  seq=IGGALGNALNGLGTWANM  words= 430
  ✅ [335/358]   36.7s  seq=NFLGTLVNLAKKIL      words= 402
  ✅ [336/358]   34.1s  seq=GMWSKILGHLIR        words= 334
  ✅ [337/358]   38.5s  seq=GLLRKGGEKIGEKLKKIG  words= 370
  ✅ [338/358]   37.7s  seq=RRSKVRICSRGKNCVSRP  words= 407
  ✅ [339/358]   35.1s  seq=GFGKAFHSVSNFAKKHKT  words= 339
  ✅ [340/358]   39.1s  seq=RCVCTRGFCRCICLLGIC  words= 432
  ✅ [341/358]   35.2s  seq=FLPLFASLIGKLL       words= 365
  ✅ [342/358]   41.2s  seq=GAIKDALKGAAKTVAVEL  words= 454

In [ ]:
def fmt(pipe_str, max_items=8):
    items = [x.strip() for x in str(pipe_str).split('|') if x.strip()][:max_items]
    return ', '.join(items)

rows = []
for idx, (seq, data) in enumerate(retrieval_results.items()):
    explanation = explanations.get(seq, '[No explanation generated]')
    props = compute_properties(seq)
    row = {
        'seq_idx':           idx + 1,
        'query_sequence':    seq,
        'query_length':      props['length'],
        'prob_amp':          round(data['prob_amp'], 6),
        'true_label':        data['true_label'],
        'prediction_result': data['result'],
        'in_starpep':        any(h.get('is_self_match', False) for h in data['hits']),
        'hydrophobicity_pct':props['hydrophobicity'],
        'net_charge':        props['net_charge'],
        'pos_charge_pct':    props['pos_charged_pct'],
        'neg_charge_pct':    props['neg_charged_pct'],
    }
    for n in range(1, TOP_K + 1):
        p = f'hit{n}_'
        if n <= len(data['hits']):
            h = data['hits'][n - 1]
            row[p+'starpep_id']    = h['id']
            row[p+'is_self_match'] = h.get('is_self_match', False)
            row[p+'cosine_sim']   = round(h['cosine_sim'], 4)
            row[p+'sequence']      = h['sequence']
            row[p+'length']        = h.get('length', len(h['sequence']))
            row[p+'activities']    = fmt(h.get('relatedTo',       ''))
            row[p+'targets']       = fmt(h.get('assessedAgainst', ''), max_items=10)
            row[p+'source']        = fmt(h.get('producedBy',      ''), max_items=4)
            row[p+'modifications'] = fmt(h.get('modifiedBy',      ''), max_items=4)
        else:
            for col in ['starpep_id','cosine_sim','sequence','length',
                        'activities','targets','source','modifications']:
                row[p+col] = ''
    row['biological_explanation'] = explanation
    rows.append(row)

results_df = pd.DataFrame(rows)
results_df.to_csv(OUTPUT_CSV, index=False, encoding='utf-8')

print(f'Results saved -> {OUTPUT_CSV}')
print(f'   Rows    : {len(results_df)}')
print(f'   Columns : {len(results_df.columns)}')
print(f'   Size    : {OUTPUT_CSV.stat().st_size / 1024:.1f} KB')
print()
print('Column layout:')
print('  [query]           seq_idx  query_sequence  query_length  prob_amp  true_label  prediction_result')
print('  [physicochemical] hydrophobicity_pct  net_charge  pos_charge_pct  neg_charge_pct')
for n in range(1, TOP_K + 1):
    print(f'  [hit {n}]           hit{n}_starpep_id  hit{n}_cosine_sim  hit{n}_sequence  hit{n}_length')
    print(f'                    hit{n}_activities  hit{n}_targets  hit{n}_source  hit{n}_modifications')
print('  [explanation]     biological_explanation')
print()
display(results_df[['query_sequence','prob_amp','prediction_result',
                     'hit1_starpep_id','hit1_cosine_sim','hit1_activities']].head(3))

Results saved -> /Users/deepugeorgejacob/Projects/amp-rag/results/amp_rag_results.csv
   Rows    : 358
   Columns : 39
   Size    : 1372.6 KB

Column layout:
  [query]           seq_idx  query_sequence  query_length  prob_amp  true_label  prediction_result
  [physicochemical] hydrophobicity_pct  net_charge  pos_charge_pct  neg_charge_pct
  [hit 1]           hit1_starpep_id  hit1_cosine_sim  hit1_sequence  hit1_length
                    hit1_activities  hit1_targets  hit1_source  hit1_modifications
  [hit 2]           hit2_starpep_id  hit2_cosine_sim  hit2_sequence  hit2_length
                    hit2_activities  hit2_targets  hit2_source  hit2_modifications
  [hit 3]           hit3_starpep_id  hit3_cosine_sim  hit3_sequence  hit3_length
                    hit3_activities  hit3_targets  hit3_source  hit3_modifications
  [explanation]     biological_explanation

,query_sequence,prob_amp,prediction_result,hit1_starpep_id,hit1_cosine_sim,hit1_activities
0,GIVDFAKKVVGGIRNALGI,0.799875,TP,starPep_00309,1.0,"Anti-Gram negative, Anti-Gram positive, Antimi..."
1,FISAIASMLGKFL,0.799397,TP,starPep_00267,1.0,"Anti-Gram positive, Antimicrobial, Antibacteri..."
2,FLPLVGKILSGLI,0.798918,TP,starPep_01728,1.0,"Antibacterial, Antimicrobial, Antifungal, Anti..."

In [ ]:
row = results_df.iloc[0]
print('=' * 80)
print(f"  seq_idx            : {row['seq_idx']}")
print(f"  query_sequence     : {row['query_sequence']}")
print(f"  prob_amp           : {row['prob_amp']:.4f}")
print(f"  prediction_result  : {row['prediction_result']}")
print(f"  net_charge         : {row['net_charge']:+d}")
print(f"  hydrophobicity_pct : {row['hydrophobicity_pct']}%")
print()
for n in range(1, TOP_K + 1):
    p = f'hit{n}_'
    print(f"  Hit #{n}: {row[p+'starpep_id']}  cosine_sim={row[p+'cosine_sim']:.2f}")
    print(f"    Sequence   : {row[p+'sequence']}")
    print(f"    Activities : {str(row[p+'activities'])[:80]}")
    print(f"    Targets    : {str(row[p+'targets'])[:80]}")
    print()
print('-' * 80)
print('  BIOLOGICAL EXPLANATION (Mistral-7B-Instruct, T=0):')
print('-' * 80)
print(row['biological_explanation'])
print('=' * 80)

================================================================================
  seq_idx            : 1
  query_sequence     : GIVDFAKKVVGGIRNALGI
  prob_amp           : 0.7999
  prediction_result  : TP
  net_charge         : +2
  hydrophobicity_pct : 52.6%

  Hit #1: starPep_00309  cosine_sim=1.00
    Sequence   : GIVDFAKKVVGGIRNALGI
    Activities : Anti-Gram negative, Anti-Gram positive, Antimicrobial, Antibacterial
    Targets    : Streptococcus uberis, Leuconostoc mesenteroides, Micrococcus luteus

  Hit #2: starPep_00302  cosine_sim=0.99
    Sequence   : GILDFAKTVVGGIRNALGI
    Activities : Antimicrobial, Anti-Gram positive, Anti-Gram negative, Antibacterial
    Targets    : Leuconostoc mesenteroides, Streptococcus uberis, Staphylococcus aureus, Listeria

  Hit #3: starPep_00295  cosine_sim=0.98
    Sequence   : GFVDLAKKVVGGIRNALGI
    Activities : Antibacterial, Antimicrobial, Anti-Gram negative, Anti-Gram positive
    Targets    : Streptococcus uberis, Leuconostoc mesenteroides, Staphylococcus aureus, Listeria

--------------------------------------------------------------------------------
  BIOLOGICAL EXPLANATION (Mistral-7B-Instruct, T=0):
--------------------------------------------------------------------------------
1. Antimicrobial Mechanism: The high hydrophobicity (52.6%) and positive net charge (+2) of the query sequence suggest that it may function as a cationic antimicrobial peptide (CAMP). CAMPs typically interact with negatively charged microbial membranes, disrupting their structure through mechanisms such as membrane depolarization, pore formation, and destabilization. The high similarity to known AMPs like starPep_00309, starPep_00302, and starPep_00295 indicates that the query sequence likely shares a similar mode of action.

2. Predicted Target Spectrum: Based on the activities of its closest neighbours, the query peptide is most likely active against Gram-positive and Gram-negative bacteria such as Streptococcus uberis, Leuconostoc mesenteroides, Staphylococcus aureus, Listeria innocua, Bacillus cereus, Escherichia coli, and Micrococcus luteus.

3. Structural Features: The structural features of the query sequence are not explicitly known, but its high similarity to known AMPs suggests that it may adopt a structure similar to those peptides. Alpha-helical structures are common in AMPs and contribute to their amphipathicity, allowing them to interact with both hydrophilic and hydrophobic regions of the microbial membrane. Key residues likely involved in activity could be identified through mutagenesis studies or computational analysis of the peptide's structure.

4. Biological Origin & Evolution: The biological context for this peptide is likely related to its source organism, Uperoleia inundata, a type of frog. AMPs are often produced by organisms as part of their innate immune response and can provide protection against pathogens. The presence of similar AMPs in the same species suggests that they may have evolved to target specific groups of bacteria commonly encountered in the frog's environment.

5. Therapeutic Potential: Given the query peptide's antimicrobial activity against a range of bacterial pathogens, it has potential as a therapeutic agent for antibacterial applications. Further research is needed to determine its efficacy against other types of microbes (e.g., fungi, viruses, and cancer cells) and to assess its safety and toxicity in mammalian systems.

6. Research Recommendations: To validate the activity of the query peptide, several experimental assays could be performed:
   - Minimum inhibitory concentration (MIC) assays to determine the peptide's effectiveness against a panel of bacterial strains.
   - Membrane permeabilization assays to investigate the mechanism by which the peptide disrupts microbial membranes.
   - Cytotoxicity assays to evaluate the peptide's safety and toxicity towards mammalian cells.
   - Structure determination techniques (e.g., NMR spectroscopy or X-ray crystallography) to elucidate the peptide's three-dimensional structure and identify key residues involved in activity.
   - Mutagenesis studies to further understand the role of specific amino acids in the peptide's function.
================================================================================