In [1]:
import os, json, pickle, time, warnings, re, requests
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch, torch.nn as nn
from transformers import BertTokenizer, BertModel

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams.update({'figure.dpi': 120, 'figure.facecolor': 'white'})

PROJECT_ROOT    = Path(os.getcwd()).parent
DATA_DIR        = PROJECT_ROOT / 'data'
RESULTS_DIR     = PROJECT_ROOT / 'results'
MODELS_DIR      = PROJECT_ROOT / 'models'

STARPEP_CSV     = DATA_DIR / 'StarPep-Metadata-Full.csv'
PREDICTIONS_CSV = RESULTS_DIR / 'test_predictions.csv'
EMBEDDINGS_NPY  = DATA_DIR / 'starpep_embeddings_cosine.npy'
METADATA_PKL    = DATA_DIR / 'starpep_metadata.pkl'
OUTPUT_CSV      = RESULTS_DIR / 'non_amp_rag_results.csv'

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO'] = '0.0'

PROTBERT_ID = 'Rostlab/prot_bert_bfd'
MAX_LEN     = 128
EMBED_BATCH = 16
TOP_K       = 3

OLLAMA_BASE_URL = 'http://localhost:11434'
OLLAMA_MODEL    = 'mistral:7b-instruct'
LLM_TEMPERATURE = 0
LLM_MAX_TOKENS  = 800

if torch.cuda.is_available():           DEVICE = 'cuda'
elif torch.backends.mps.is_available(): DEVICE = 'mps'
else:                                   DEVICE = 'cpu'

def clear_memory():
    if DEVICE == 'mps':  torch.mps.empty_cache()
    elif DEVICE == 'cuda': torch.cuda.empty_cache()

In [ ]:
def ollama_health_check(base_url: str, model: str) -> bool:
    """Return True if Ollama is running and the model is available."""
    try:
        r = requests.get(f"{base_url}/api/tags", timeout=5)
        r.raise_for_status()
        models_available = [m["name"] for m in r.json().get("models", [])]
        print(f"Ollama server   : ✅ running")
        print(f"Models loaded   : {models_available}")

        if model in models_available:
            print(f"Target model    : ✅ {model} ready")
            return True
        else:
            print(f"Target model    : ❌ '{model}' not found")
            print(f"  Run: ollama pull {model}")
            return False

    except requests.exceptions.ConnectionError:
        print("❌ Ollama not reachable — start it with: ollama serve")
        return False
    except Exception as e:
        print(f"❌ Health check failed: {e}")
        return False

OLLAMA_READY = ollama_health_check(OLLAMA_BASE_URL, OLLAMA_MODEL)

if OLLAMA_READY:
    print("\nWarm-up call (loads model weights)...")
    r = requests.post(
        f"{OLLAMA_BASE_URL}/api/chat",
        json={
            "model":    OLLAMA_MODEL,
            "messages": [{"role": "user", "content": "What is an antimicrobial peptide? One sentence."}],
            "stream":   False,
            "options":  {"temperature": LLM_TEMPERATURE, "num_predict": 60},
        },
        timeout=120,
    )
    warmup_reply = r.json()["message"]["content"].strip()
    print(f"✅ Model warm-up OK: {warmup_reply[:120]}")
else:
    print("\n⚠️  Fix Ollama before running Section 6.")

Ollama server   : ✅ running
Models loaded   : ['mistral:7b-instruct']
Target model    : ✅ mistral:7b-instruct ready

Warm-up call (loads model weights)...
✅ Model warm-up OK: Antimicrobial peptides are small, naturally occurring proteins that possess the ability to destroy microorganisms such a

In [ ]:
starpep_df = pd.read_csv(STARPEP_CSV)

starpep_df["sequence"] = starpep_df["sequence"].astype(str).str.strip().str.upper()
starpep_df = starpep_df[starpep_df["sequence"].str.len() > 0].reset_index(drop=True)

meta_cols = ["assessedAgainst", "relatedTo", "producedBy", "modifiedBy",
             "compiledIn", "linkedTo", "constitutedBy"]
for col in meta_cols:
    if col in starpep_df.columns:
        starpep_df[col] = starpep_df[col].fillna("").astype(str)

print(f"StarPep records     : {len(starpep_df):,}")
print(f"Columns             : {starpep_df.columns.tolist()}")
print(f"\nSequence length stats:")
print(starpep_df["length"].describe().round(1))
starpep_df.head(3)

StarPep records     : 45,120
Columns             : ['id', 'sequence', 'length', 'assessedAgainst', 'compiledIn', 'constitutedBy', 'linkedTo', 'modifiedBy', 'producedBy', 'relatedTo']

Sequence length stats:
count    45120.0
mean        27.0
std         21.7
min          2.0
25%         12.0
50%         19.0
75%         35.0
max        100.0
Name: length, dtype: float64

,id,sequence,length,assessedAgainst,compiledIn,constitutedBy,linkedTo,modifiedBy,producedBy,relatedTo
0,starPep_00000,GIGAVLKVLTTGLPALISWIKRKRQQ,26,HIV|Xanthomonas oryzae|Propionibacterium acnes...,HIPdb|ADAM|DRAMP_Patent|StraPep|AntiTbPdb|RAPD...,P at position 14 is D Proline|V at position 8 ...,PubMed: 23150226|PubMed: 10217411|PubMed: 2389...,Amidation|Lac=P-Amidophenyl-Β-D-Lactopyranosid...,Insecta|Apis cerana|Polistes|Apis mellifera|Sy...,Antifungal|Antibacterial|Antibiofilm|Toxic|Ant...
1,starPep_00001,GIGKFLHSAKKFGKAFVGEIMNS,23,Leukemia cancer|Serratia marcescens|Enterococc...,AMSDb|SATPdb|ADAM|AntiTbPdb|LAMP_Experimental|...,E at position 19 is D Glutamic Acid|K at posit...,PubMed: 9090128|DOI: 10.1093/jac/dkl120|PubMed...,Amidation,Synthetic construct|Xenopus ruwenzoriensis|Amp...,Toxic to mammals|Antiparasitic|Antibacterial|A...
2,starPep_00002,ILPWKWPWWPWRR,13,Streptococcus pyogenes|Sheep erythrocytes|Micr...,HIPdb|StraPep|AMSDb|CAMP_Validated|CAMP_Patent...,I at position 1 is D Isoleucine|W at position ...,PubMed: 11061996|PubMed: 16998183|PubMed: 1092...,Amidation|Acetylation,Bos taurus|Streptococcus equi|Synthetic construct,Surface-immobilization|Antibiofilm|Antileishma...

In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    PROTBERT_ID, do_lower_case=False, cache_dir=str(MODELS_DIR)
)
encoder = BertModel.from_pretrained(PROTBERT_ID, cache_dir=str(MODELS_DIR))
encoder = encoder.to(DEVICE)
encoder.eval()

total_params = sum(p.numel() for p in encoder.parameters())
print(f"✅ ProtBERT-BFD loaded  ({total_params/1e6:.0f}M params, device={DEVICE})")

✅ ProtBERT-BFD loaded  (420M params, device=mps)

In [ ]:
@torch.no_grad()
def embed_sequences(sequences: list[str],
                    tokenizer,
                    model,
                    device: str,
                    batch_size: int = EMBED_BATCH,
                    max_len: int = MAX_LEN) -> np.ndarray:
    """
    Embed a list of amino-acid sequences using ProtBERT-BFD.
    Returns a (N, 1024) float32 numpy array of [CLS] embeddings.
    """
    all_embeddings = []
    n_batches = (len(sequences) + batch_size - 1) // batch_size

    for i in range(0, len(sequences), batch_size):
        batch = sequences[i : i + batch_size]
        batch_num = i // batch_size + 1

        spaced = [" ".join(list(seq.upper().replace(" ", ""))) for seq in batch]

        enc = tokenizer(
            spaced,
            max_length=max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        input_ids = enc["input_ids"].to(device)
        attn_mask = enc["attention_mask"].to(device)

        out = model(input_ids=input_ids, attention_mask=attn_mask)
        cls_emb = out.last_hidden_state[:, 0, :].cpu().float().numpy()
        all_embeddings.append(cls_emb)

        del input_ids, attn_mask, out
        clear_memory()

        if batch_num % 20 == 0 or batch_num == n_batches:
            pct = batch_num / n_batches * 100
            print(f"  [{batch_num:4d}/{n_batches}]  {pct:5.1f}%  "
                  f"processed {min(i+batch_size, len(sequences)):4d}/{len(sequences)} seqs",
                  flush=True)

    return np.vstack(all_embeddings)   # (N, 1024)


print("Embedding function defined.")

Embedding function defined.

In [ ]:
if EMBEDDINGS_NPY.exists() and METADATA_PKL.exists():
    print('Cached embeddings found — loading...')
    store_embeddings = np.load(EMBEDDINGS_NPY)
    with open(METADATA_PKL, 'rb') as f:
        store_metadata = pickle.load(f)
    print(f'   Shape : {store_embeddings.shape}  (L2-normalised unit vectors)')
    print(f'   Meta  : {len(store_metadata)} records')
else:
    print(f'Embedding {len(starpep_df):,} StarPep sequences...')
    t0 = time.time()
    raw_embeddings = embed_sequences(starpep_df['sequence'].tolist(),
                                     tokenizer, encoder, DEVICE)

    norms = np.linalg.norm(raw_embeddings, axis=1, keepdims=True)
    store_embeddings = raw_embeddings / np.clip(norms, 1e-9, None)
    np.save(EMBEDDINGS_NPY, store_embeddings)
    print(f'\nL2-normalised embeddings saved -> {EMBEDDINGS_NPY.name}  {store_embeddings.shape}')

    store_metadata = []
    for _, row in starpep_df.iterrows():
        store_metadata.append({
            'id':              row['id'],
            'sequence':        row['sequence'],
            'length':          row.get('length', len(row['sequence'])),
            'assessedAgainst': row.get('assessedAgainst', ''),
            'relatedTo':       row.get('relatedTo', ''),
            'producedBy':      row.get('producedBy', ''),
            'modifiedBy':      row.get('modifiedBy', ''),
            'compiledIn':      row.get('compiledIn', ''),
            'linkedTo':        row.get('linkedTo', ''),
        })
    with open(METADATA_PKL, 'wb') as f:
        pickle.dump(store_metadata, f)
    print(f'Metadata saved -> {METADATA_PKL.name}  ({len(store_metadata)} records)')
    print(f'Time : {(time.time()-t0)/60:.1f} min')

sample_norms = np.linalg.norm(store_embeddings[:5], axis=1)
print(f'\nSample L2 norms (should be 1.0): {sample_norms.round(6)}')
print(f'Vector store ready — {store_embeddings.shape[0]:,} unit-norm AMPs @ {store_embeddings.shape[1]}-d')
print('Similarity: cosine  (store @ query.T  since both are unit vectors)')

Cached embeddings found — loading...
   Shape : (2949, 1024)  (L2-normalised unit vectors)
   Meta  : 2949 records

Sample L2 norms (should be 1.0): [1. 1. 1. 1. 1.]
Vector store ready — 2,949 unit-norm AMPs @ 1024-d
Similarity: cosine  (store @ query.T  since both are unit vectors)

In [ ]:
pred_df = pd.read_csv(PREDICTIONS_CSV)
print(f"Total test predictions : {len(pred_df):,}")
print(f"Class distribution     : {pred_df['predicted'].value_counts().to_dict()}")

neg_df = pred_df[pred_df["predicted"] == 0].reset_index(drop=True)
print(f"\nNegative (non-AMP) predictions : {len(neg_df):,}")
print(f"  True Negatives (TN)          : {(neg_df['result']=='TN').sum()}")
print(f"  False Negatives (FN)         : {(neg_df['result']=='FN').sum()}")
neg_df.head(5)

Total test predictions : 712
Class distribution     : {1: 358, 0: 354}

Negative (non-AMP) predictions : 354
  True Negatives (TN)          : 321
  False Negatives (FN)         : 33

,sequence,aa_length,label,prob_amp,predicted,correct,result
0,VVRVGGRVPVLAGTGLSGTAKT,22,0,0.276276,0,1,TN
1,LEPGVVIGYDR,11,0,0.270477,0,1,TN
2,FEDAALIPSGQKAAFLKATDTLLSAVTECWRTDFATLRLHGDCHAG...,88,0,0.297874,0,1,TN
3,LPHHVFPPKKITTTQLGQLAGVQYYKVDLDDTASMKK,37,0,0.271006,0,1,TN
4,GQIFQDDFDPESEQNQKLEDCARQLNRIFTLCLNDRAPLEESRKWG...,62,0,0.270393,0,1,TN

In [ ]:
def retrieve_top_k(query_seq, store_embs, store_meta, tokenizer, model, device, top_k=TOP_K):
    query_emb = embed_sequences([query_seq], tokenizer, model, device, batch_size=1)
    query_unit = query_emb / np.clip(np.linalg.norm(query_emb), 1e-9, None)

    cosine_scores = (store_embs @ query_unit.T).squeeze()
    top_idx = np.argsort(cosine_scores)[::-1][:top_k]
    results = []
    for rank, idx in enumerate(top_idx, start=1):
        meta = dict(store_meta[idx])
        meta['rank']        = rank
        meta['cosine_sim']  = round(float(cosine_scores[idx]), 6)
        meta['is_self_match'] = (meta['cosine_sim'] >= 0.9999 and
                                  store_meta[idx]['sequence'].upper() == query_seq.upper())
        results.append(meta)
    return results

print('Retrieval function ready — cosine similarity, self-match included (score=1.0 flags known AMP).')

Retrieval function ready — cosine similarity, self-match included (score=1.0 flags known AMP).

In [ ]:
demo_seq = neg_df['sequence'].iloc[0]
print(f"Query : {demo_seq}  (len={len(demo_seq)} aa,  prob={neg_df['prob_amp'].iloc[0]:.4f})")
print('\nRetrieving top-3 via cosine similarity...')
demo_results = retrieve_top_k(demo_seq, store_embeddings, store_metadata,
                               tokenizer, encoder, DEVICE)
print(f"\n{'Rank':<5} {'CosineSim':>10}  {'Self?':>5}  {'ID':<18} {'Seq':<30} {'Activities (first 3)'}")
print('-' * 115)
for r in demo_results:
    acts = ', '.join(r['relatedTo'].split('|')[:3]) if r['relatedTo'] else 'N/A'
    flag = ' ✓ SELF' if r['is_self_match'] else ''
    print(f"#{r['rank']:<4} {r['cosine_sim']:>10.6f}  {'YES' if r['is_self_match'] else 'no':>5}  {r['id']:<18} {r['sequence'][:28]:<30} {acts}{flag}")
print()
self_match = next((r for r in demo_results if r['is_self_match']), None)
if self_match:
    print(f"⚠️  Exact self-match found at rank {self_match['rank']} — this non-AMP sequence IS in StarPep APD (cosine=1.0); may be a false negative)")
else:
    print('ℹ️  No exact self-match in top-3 — sequence is not in StarPep APD (expected for non-AMPs)')

Query : VVRVGGRVPVLAGTGLSGTAKT  (len=22 aa,  prob=0.2763)

Retrieving top-3 via cosine similarity...
  [   1/1]  100.0%  processed    1/1 seqs

Rank   CosineSim  Self?  ID                 Seq                            Activities (first 3)
-------------------------------------------------------------------------------------------------------------------
#1      0.957302     no  starPep_04826      VGVGGGFGR                      Anti-Gram negative, Toxic to mammals, Anti-Gram positive
#2      0.956079     no  starPep_02065      AKAWGIPPHVIPQIVPVRIRPLCGNV     Antifungal, Anti-Gram positive, Antioxidant
#3      0.949847     no  starPep_07912      VSGPAGPPGTH                    Antifungal, Anti-Gram positive

ℹ️  No exact self-match in top-3 — sequence is not in StarPep APD (expected for non-AMPs)

In [ ]:
print(f"Retrieving top-{TOP_K} similar AMPs for {len(neg_df):,} negative predictions...")
print("(Each query embeds one sequence — may take a few minutes)\n")

retrieval_results = {}

for idx, row in neg_df.iterrows():
    seq = row["sequence"]
    hits = retrieve_top_k(seq, store_embeddings, store_metadata,
                          tokenizer, encoder, DEVICE)
    retrieval_results[seq] = {
        "sequence":  seq,
        "prob_amp":  row["prob_amp"],
        "true_label":int(row["label"]),
        "result":    row["result"],
        "hits":      hits,
    }
    if (idx + 1) % 50 == 0 or (idx + 1) == len(neg_df):
        print(f"  [{idx+1:>3}/{len(neg_df)}] done", flush=True)

clear_memory()
print(f"\n✅ Retrieval complete for {len(retrieval_results):,} sequences.")

Retrieving top-3 similar AMPs for 354 negative predictions...
(Each query embeds one sequence — may take a few minutes)

  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [ 50/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [100/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [150/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [200/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [250/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [300/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [350/354] done
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [   1/1]  100.0%  processed    1/1 seqs
  [354/354] done

✅ Retrieval complete for 354 sequences.

In [ ]:
HYDROPHOBIC = set("AVILMFYW")
CHARGED_POS = set("KRH")
CHARGED_NEG = set("DE")

def compute_properties(seq: str) -> dict:
    seq = seq.upper()
    n = len(seq)
    hydrophobic_count = sum(1 for aa in seq if aa in HYDROPHOBIC)
    pos_charge  = sum(1 for aa in seq if aa in CHARGED_POS)
    neg_charge  = sum(1 for aa in seq if aa in CHARGED_NEG)
    net_charge  = pos_charge - neg_charge
    return {
        "length":          n,
        "hydrophobicity":  round(hydrophobic_count / n * 100, 1),
        "net_charge":      net_charge,
        "pos_charged_pct": round(pos_charge / n * 100, 1),
        "neg_charged_pct": round(neg_charge / n * 100, 1),
    }


def format_activities(pipe_str: str, max_items: int = 6) -> str:
    """Convert pipe-separated string to a comma-separated short list."""
    items = [x.strip() for x in pipe_str.split("|") if x.strip()][:max_items]
    return ", ".join(items) if items else "Not specified"


def format_targets(pipe_str: str, max_items: int = 8) -> str:
    items = [x.strip() for x in pipe_str.split("|") if x.strip()][:max_items]
    return ", ".join(items) if items else "Not specified"


def build_prompt(query_seq: str,
                 prob_amp: float,
                 hits: list[dict]) -> str:
    """
    Construct an expert-level biological prompt explaining why a sequence
    is NOT predicted as an antimicrobial peptide.
    """
    props = compute_properties(query_seq)

    hit_sections = []
    for h in hits:
        activities = format_activities(h.get("relatedTo", ""))
        targets    = format_targets(h.get("assessedAgainst", ""))
        source     = format_activities(h.get("producedBy", ""), max_items=3)
        mods       = format_activities(h.get("modifiedBy", ""), max_items=3)

        hit_sections.append(
            f"  [{h['rank']}] ID: {h['id']}  Similarity: {h['cosine_sim']:.4f}\n"
            f"      Sequence     : {h['sequence']}  (length: {h.get('length', len(h['sequence']))} aa)\n"
            f"      Activities   : {activities}\n"
            f"      Target organisms: {targets}\n"
            f"      Biological source: {source}\n"
            f"      Modifications : {mods if mods != 'Not specified' else 'None reported'}"
        )

    hits_text = "\n\n".join(hit_sections)

    prompt = f"""You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be NON-antimicrobial (not an AMP) with AMP probability {prob_amp:.4f}:

QUERY SEQUENCE: {query_seq}

PHYSICOCHEMICAL PROPERTIES:
  • Length         : {props["length"]} amino acids
  • Hydrophobicity : {props["hydrophobicity"]}% hydrophobic residues ({", ".join(HYDROPHOBIC & set(query_seq.upper()))})
  • Net charge     : {props["net_charge"]:+d} (Positive residues: {props["pos_charged_pct"]}%, Negative: {props["neg_charged_pct"]}%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BFD embedding space):

{hits_text}

The classifier predicts the query sequence as NOT an AMP. Based on sequences retrieved from the embedding space and the query peptide sequence, provide a comprehensive biological explanation on why it is prediceted as NOT an AMP covering:

1. MISSING AMP FEATURES — What key physicochemical properties (charge, hydrophobicity, amphipathicity, length) that are hallmarks of AMPs does this sequence lack or have at insufficient levels?
2. CONTRAST WITH AMP NEIGHBOURS — How does this sequence differ from its closest retrieved AMP neighbours? What specific residue differences reduce or eliminate antimicrobial potential?
3. STRUCTURAL DEFICIENCIES — What structural motifs (alpha-helix, amphipathic structure, beta-sheet) are likely absent or disrupted? Which residues break the pattern?
4. PHYSICOCHEMICAL BARRIERS — Why would the charge distribution or hydrophobic profile prevent effective interaction with microbial membranes compared to canonical AMPs?
5. POTENTIAL ALTERNATIVE FUNCTION — If not antimicrobial, what other biological role might this sequence serve (e.g., structural protein, signalling peptide, enzyme)?
6. MODIFICATIONS FOR AMP ACTIVITY — What minimal amino acid substitutions or modifications might theoretically confer AMP activity to this sequence?

Be specific, cite amino acid positions where relevant, and ground your explanation in the contrast with the retrieved data."""

    return prompt


print("Prompt builder defined.")
print("\nSample prompt for demo sequence:")
print("-"*60)
sample_prompt = build_prompt(
    demo_seq, neg_df['prob_amp'].iloc[0], demo_results
)
print(sample_prompt[:600], "...")

Prompt builder defined.

Sample prompt for demo sequence:
------------------------------------------------------------
You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be NON-antimicrobial (not an AMP) with AMP probability 0.2763:

QUERY SEQUENCE: VVRVGGRVPVLAGTGLSGTAKT

PHYSICOCHEMICAL PROPERTIES:
  • Length         : 22 amino acids
  • Hydrophobicity : 40.9% hydrophobic residues (V, A, L)
  • Net charge     : +3 (Positive residues: 13.6%, Negative: 0.0%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BF ...

In [ ]:
print(sample_prompt)

You are an expert computational biologist specialising in antimicrobial peptides (AMPs) and protein bioinformatics.

A machine-learning classifier (ProtBERT-BFD fine-tuned on the Veltri dataset) has predicted the following peptide sequence to be NON-antimicrobial (not an AMP) with AMP probability 0.2763:

QUERY SEQUENCE: VVRVGGRVPVLAGTGLSGTAKT

PHYSICOCHEMICAL PROPERTIES:
  • Length         : 22 amino acids
  • Hydrophobicity : 40.9% hydrophobic residues (V, A, L)
  • Net charge     : +3 (Positive residues: 13.6%, Negative: 0.0%)

TOP-3 MOST SIMILAR KNOWN AMPs (cosine similarity in ProtBERT-BFD embedding space):

  [1] ID: starPep_04826  Similarity: 0.9573
      Sequence     : VGVGGGFGR  (length: 9 aa)
      Activities   : Anti-Gram negative, Toxic to mammals, Anti-Gram positive, Antibacterial
      Target organisms: Vibrio cholerae, Pseudomonas aeruginosa, Staphylococcus aureus, Human erythrocytes, Escherichia coli
      Biological source: Not specified
      Modifications : Amidation

  [2] ID: starPep_02065  Similarity: 0.9561
      Sequence     : AKAWGIPPHVIPQIVPVRIRPLCGNV  (length: 26 aa)
      Activities   : Antifungal, Anti-Gram positive, Antioxidant, Antimicrobial, Antibacterial, Anti-Gram negative
      Target organisms: Escherichia coli, Candida albicans, Bacillus subtilis, Staphylococcus aureus
      Biological source: Babina pleuraden
      Modifications : None reported

  [3] ID: starPep_07912  Similarity: 0.9498
      Sequence     : VSGPAGPPGTH  (length: 11 aa)
      Activities   : Antifungal, Anti-Gram positive
      Target organisms: Aspergillus niger, Listeria monocytogenes, Bacillus cereus
      Biological source: Lactobacillus plantarum
      Modifications : None reported

The classifier predicts the query sequence as NOT an AMP. Based on sequences retrieved from the embedding space and the query peptide sequence, provide a comprehensive biological explanation on why it is prediceted as NOT an AMP covering:

1. MISSING AMP FEATURES — What key physicochemical properties (charge, hydrophobicity, amphipathicity, length) that are hallmarks of AMPs does this sequence lack or have at insufficient levels?
2. CONTRAST WITH AMP NEIGHBOURS — How does this sequence differ from its closest retrieved AMP neighbours? What specific residue differences reduce or eliminate antimicrobial potential?
3. STRUCTURAL DEFICIENCIES — What structural motifs (alpha-helix, amphipathic structure, beta-sheet) are likely absent or disrupted? Which residues break the pattern?
4. PHYSICOCHEMICAL BARRIERS — Why would the charge distribution or hydrophobic profile prevent effective interaction with microbial membranes compared to canonical AMPs?
5. POTENTIAL ALTERNATIVE FUNCTION — If not antimicrobial, what other biological role might this sequence serve (e.g., structural protein, signalling peptide, enzyme)?
6. MODIFICATIONS FOR AMP ACTIVITY — What minimal amino acid substitutions or modifications might theoretically confer AMP activity to this sequence?

Be specific, cite amino acid positions where relevant, and ground your explanation in the contrast with the retrieved data.

In [ ]:
def query_llm(prompt: str,
              model:  str    = OLLAMA_MODEL,
              base_url: str  = OLLAMA_BASE_URL,
              max_tokens: int = LLM_MAX_TOKENS,
              temperature: float = LLM_TEMPERATURE,
              retries: int = 3) -> str:
    """
    Send a chat prompt to the local Ollama instance.
    temperature=0 → greedy decoding → fully deterministic output.
    Returns the generated explanation text.
    """
    payload = {
        "model":  model,
        "stream": False,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an expert computational biologist specialising in "
                    "antimicrobial peptides (AMPs). Provide detailed, scientifically "
                    "accurate biological explanations using structured headings. "
                    "Base your answer strictly on the provided sequence data and "
                    "retrieved similar AMPs."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "options": {
            "temperature": temperature,
            "num_predict": max_tokens,
            "top_p":       1.0,
            "top_k":       1,
        },
    }

    for attempt in range(1, retries + 1):
        try:
            resp = requests.post(
                f"{base_url}/api/chat",
                json=payload,
                timeout=300,
            )
            resp.raise_for_status()
            return resp.json()["message"]["content"].strip()
        except requests.exceptions.Timeout:
            print(f"  ⚠️  Timeout on attempt {attempt}/{retries}. Retrying...")
        except requests.exceptions.ConnectionError:
            print(f"  ❌ Ollama not reachable. Is 'ollama serve' running?")
            return "[LLM ERROR] Ollama not reachable."
        except Exception as e:
            wait = 2 ** attempt
            print(f"  ⚠️  Attempt {attempt}/{retries} failed: {e}. Retrying in {wait}s...")
            time.sleep(wait)

    return f"[LLM ERROR] Could not generate explanation after {retries} attempts."


print(f"✅ Ollama LLM function ready")
print(f"   Model       : {OLLAMA_MODEL}")
print(f"   Temperature : {LLM_TEMPERATURE}  (greedy / deterministic)")
print(f"   top_k       : 1  (greedy decoding)")
print(f"   Max tokens  : {LLM_MAX_TOKENS}")

✅ Ollama LLM function ready
   Model       : mistral:7b-instruct
   Temperature : 0  (greedy / deterministic)
   top_k       : 1  (greedy decoding)
   Max tokens  : 800

In [ ]:
if not OLLAMA_READY:
    raise RuntimeError("Ollama is not running. Start it with: ollama serve")

print(f"Generating biological explanations for {len(retrieval_results):,} sequences...")
print(f"LLM   : {OLLAMA_MODEL}  (local Ollama)")
print(f"Temp  : {LLM_TEMPERATURE}  — deterministic greedy decoding\n")

explanations = {}
failed_seqs  = []
t_start = time.time()

for i, (seq, data) in enumerate(list(retrieval_results.items()), start=1):
    t0          = time.time()
    prompt      = build_prompt(seq, data["prob_amp"], data["hits"])
    explanation = query_llm(prompt)
    elapsed_seq = time.time() - t0

    explanations[seq] = explanation

    status = "✅" if "[LLM ERROR]" not in explanation else "❌"
    if "[LLM ERROR]" in explanation:
        failed_seqs.append(seq)

    print(f"  {status} [{i:>3}/{len(retrieval_results)}]  "
          f"{elapsed_seq:5.1f}s  seq={seq[:18]:<18}  "
          f"words={len(explanation.split()):>4}", flush=True)

total_elapsed = time.time() - t_start
print(f"\n{'─'*60}")
print(f"✅ Explanations generated : {len(explanations) - len(failed_seqs):,}")
print(f"❌ Failed                : {len(failed_seqs)}")
print(f"⏱  Total time            : {total_elapsed/60:.1f} min  "
      f"({total_elapsed/len(retrieval_results):.1f}s per sequence)")

Generating biological explanations for 354 sequences...
LLM   : mistral:7b-instruct  (local Ollama)
Temp  : 0  — deterministic greedy decoding

  ✅ [  1/354]   42.8s  seq=VVRVGGRVPVLAGTGLSG  words= 458
  ✅ [  2/354]   38.6s  seq=LEPGVVIGYDR         words= 415
  ✅ [  3/354]   38.8s  seq=FEDAALIPSGQKAAFLKA  words= 413
  ✅ [  4/354]   37.6s  seq=LPHHVFPPKKITTTQLGQ  words= 431
  ✅ [  5/354]   40.9s  seq=GQIFQDDFDPESEQNQKL  words= 464
  ✅ [  6/354]   35.1s  seq=LTTKLWSSWGYYLGKKAR  words= 377
  ✅ [  7/354]   38.9s  seq=PPTPAPQHSDLCLAMAVQ  words= 453
  ✅ [  8/354]   41.5s  seq=KQGAEICMCREFYQFLTA  words= 458
  ✅ [  9/354]   39.0s  seq=IVNLNNGQRWLTYVLPGQ  words= 427
  ✅ [ 10/354]   40.3s  seq=RTYRAMYDYSAQDEDEVS  words= 444
  ✅ [ 11/354]   41.4s  seq=LVKLGDTMVLA         words= 450
  ✅ [ 12/354]   41.6s  seq=ASVVTELRCQCLQTLQGI  words= 471
  ✅ [ 13/354]   41.9s  seq=DSFKKAHGRTKDTREQRE  words= 454
  ✅ [ 14/354]   43.2s  seq=EGQATHTGPKGVINDWRK  words= 459
  ✅ [ 15/354]   41.8s  seq=RDNAILLDQTIFYPTGGG  words= 428
  ✅ [ 16/354]   41.1s  seq=VPYVKATEPHMLETYTPE  words= 448
  ✅ [ 17/354]   41.4s  seq=DSTDFFKSGAASVDVV    words= 449
  ✅ [ 18/354]   41.3s  seq=FKADNQHFCFKKINITKK  words= 468
  ✅ [ 19/354]   42.6s  seq=TMHITTKLGMNFVHISPK  words= 439
  ✅ [ 20/354]   38.8s  seq=SESSNVTFLRNILDCLRD  words= 445
  ✅ [ 21/354]   41.9s  seq=HYGVVDYLIKPFQASRFE  words= 462
  ✅ [ 22/354]   41.1s  seq=SVKGLNKEELEDRLLPHQ  words= 446
  ✅ [ 23/354]   41.5s  seq=TIFRNQILFKDFTKLNAR  words= 484
  ✅ [ 24/354]   40.9s  seq=DILESLHQALPNMALLAY  words= 460
  ✅ [ 25/354]   42.3s  seq=RTLVIGCDSVLEFDGQIF  words= 488
  ✅ [ 26/354]   41.9s  seq=FDRGKYVSTRIREMMIKG  words= 441
  ✅ [ 27/354]   39.6s  seq=IAFMVKAVVLDPTNHFNV  words= 417
  ✅ [ 28/354]   41.4s  seq=LDWKLDDNYAMYCLTE    words= 448
  ✅ [ 29/354]   38.3s  seq=MTVGTTVDEAAYLLSLME  words= 412
  ✅ [ 30/354]   39.6s  seq=ANIIGNKMSAISVHG     words= 441
  ✅ [ 31/354]   42.0s  seq=VGGLPYHTTDASLRKYFE  words= 464
  ✅ [ 32/354]   40.5s  seq=QNQGSQESPSEDVLPFLS  words= 467
  ✅ [ 33/354]   37.8s  seq=FSKYERQKDKRPYSERKN  words= 384
  ✅ [ 34/354]   40.6s  seq=HYLYAQTSNMVIN       words= 453
  ✅ [ 35/354]   41.2s  seq=LHQHVEKHLLKDIREMFQ  words= 430
  ✅ [ 36/354]   41.0s  seq=KLGVERDGHMPSGTVLLE  words= 479
  ✅ [ 37/354]   39.2s  seq=RNARFCDDRVHALIYFIS  words= 413
  ✅ [ 38/354]   42.1s  seq=TIAMARTSDPHSATAQFF  words= 478
  ✅ [ 39/354]   39.2s  seq=NNNIINNNNSQSNLQSLL  words= 421
  ✅ [ 40/354]   41.3s  seq=TDIPSGKFTSKWPTQLEK  words= 452
  ✅ [ 41/354]   40.2s  seq=NKKNNNNSDDVLPFISES  words= 431
  ✅ [ 42/354]   41.6s  seq=RSFKNYTGPYIELGNCYN  words= 457
  ✅ [ 43/354]   41.9s  seq=YVLVNETEKIDLVEFLSH  words= 473
  ✅ [ 44/354]   39.8s  seq=KPLTAIQADLTHSIDLLP  words= 460
  ✅ [ 45/354]   39.7s  seq=RKINYQIRLATLSDIDQI  words= 424
  ✅ [ 46/354]   42.3s  seq=LLPGATSLYYWEGKLEQE  words= 476
  ✅ [ 47/354]   41.5s  seq=MEGFLGLEVLLTENTKDF  words= 450
  ✅ [ 48/354]   39.3s  seq=LDSNHRKAFDSLRQELQT  words= 428
  ✅ [ 49/354]   41.8s  seq=PLVEIKEPSKVIAQSTEE  words= 437
  ✅ [ 50/354]   41.4s  seq=LQMKDEIAATII        words= 465
  ✅ [ 51/354]   39.0s  seq=EQTVKLLRHRIL        words= 443
  ✅ [ 52/354]   36.5s  seq=SQLEVKAMPTFLFLKDGN  words= 402
  ✅ [ 53/354]   41.1s  seq=KKKSGVIPTVSHDCHMNS  words= 438
  ✅ [ 54/354]   42.0s  seq=LYIPEHKTGGWTNHNPRR  words= 452
  ✅ [ 55/354]   40.7s  seq=MSQEKIEDMLCRDELDVG  words= 430
  ✅ [ 56/354]   40.9s  seq=VVPTLRFFYDEGPDAERR  words= 450
  ✅ [ 57/354]   40.7s  seq=EISDEMKAICNLQLGK    words= 460
  ✅ [ 58/354]   41.1s  seq=FTKETDFSEITTDSSVLP  words= 444
  ✅ [ 59/354]   39.5s  seq=EDKLSLRRHPERPIPEHN  words= 423
  ✅ [ 60/354]   40.9s  seq=EDIKNVVLQYGFKVE     words= 461
  ✅ [ 61/354]   39.6s  seq=SKTRSQEQAKEYSNTW    words= 433
  ✅ [ 62/354]   42.1s  seq=ILKRVAANALMSLLAVSR  words= 442
  ✅ [ 63/354]   41.1s  seq=FTSKKSMLLFFFLGTISL  words= 436
  ✅ [ 64/354]   41.1s  seq=FANLTTETKTTDSSAVST  words= 428
  ✅ [ 65/354]   37.2s  seq=PYGDKIVTGSFDKTCKLW  words= 393
  ✅ [ 66/354]   41.1s  seq=NDYNFKVGAKCKVELPNE  words= 452
  ✅ [ 67/354]   39.5s  seq=VLEAVGGKVWVIPGISAN  words= 433
  ✅ [ 68/354]   41.1s  seq=SLPHGCLLPSDLINSHWS  words= 460
  ✅ [ 69/354]   40.9s  seq=IKVEPVPPKGLEFKIPGD  words= 483
  ✅ [ 70/354]   40.9s  seq=ELIDRCIGSKIWVIMKGD  words= 453
  ✅ [ 71/354]   39.4s  seq=GSPSQCPNILGPIRFGDD  words= 425
  ✅ [ 72/354]   41.2s  seq=STVTLPLRKDTVLFSLVT  words= 463
  ✅ [ 73/354]   40.7s  seq=QENDVPVIVVSSGMKPII  words= 472
  ✅ [ 74/354]   41.1s  seq=EGGIQSIATAMKNH      words= 431
  ✅ [ 75/354]   41.2s  seq=GEVAVHQMTGYSEGELYI  words= 475
  ✅ [ 76/354]   40.1s  seq=WGMAFRIPAKYATQVREY  words= 424
  ✅ [ 77/354]   40.2s  seq=KSSYTMSPSHAPPRS     words= 434
  ✅ [ 78/354]   41.2s  seq=VHRMIIAAVRLSTKLLED  words= 484
  ✅ [ 79/354]   39.2s  seq=GTAQAPSLVLKEKEPNTS  words= 426
  ✅ [ 80/354]   41.8s  seq=SMATPHVAGAAALILSKH  words= 476
  ✅ [ 81/354]   37.6s  seq=VVRTREEKDERNLQISLT  words= 433
  ✅ [ 82/354]   37.1s  seq=EEQSFTAEVVGYESEAQM  words= 403
  ✅ [ 83/354]   40.7s  seq=LPVYDHGAVMQDDDT     words= 451
  ✅ [ 84/354]   39.8s  seq=KEEQEWEALEYQGRKAHR  words= 432
  ✅ [ 85/354]   39.4s  seq=LLQDKDSLMNALQASHDA  words= 447
  ✅ [ 86/354]   38.1s  seq=INDFPTENFMDTEKNV    words= 428
  ✅ [ 87/354]   41.7s  seq=TDITHVNENILKDINEEI  words= 406
  ✅ [ 88/354]   39.8s  seq=DVLEYLREQTEHPDHYIF  words= 429
  ✅ [ 89/354]   41.8s  seq=TENEANKSTDDPSQLSV   words= 479
  ✅ [ 90/354]   41.0s  seq=PSTTPAPSTTSAPTTTTT  words= 436
  ✅ [ 91/354]   41.6s  seq=KQIMTQFFNFARSPAVKD  words= 435
  ✅ [ 92/354]   41.6s  seq=NHETSVKVSKNKKSVKLL  words= 465
  ✅ [ 93/354]   42.0s  seq=CSFMLDSVGGSLPKKSIP  words= 454
  ✅ [ 94/354]   42.5s  seq=REQDEILAIIDKNWQTLH  words= 457
  ✅ [ 95/354]   42.7s  seq=LVHKTDEDKVMVLDSHKL  words= 446
  ✅ [ 96/354]   40.0s  seq=LETLDDFRSAQELHDELR  words= 421
  ✅ [ 97/354]   41.8s  seq=TWKPDRNTPDTVYYHC    words= 463
  ✅ [ 98/354]   39.9s  seq=MNEIALMPSPPSRNEQPA  words= 428
  ✅ [ 99/354]   42.1s  seq=YSLKKTSMKIIPFTRL    words= 447
  ✅ [100/354]   42.2s  seq=LLDIHGVSDHLTIDLGEV  words= 454
  ✅ [101/354]   42.8s  seq=DDLLHFRPSSTYGFCTQI  words= 441
  ✅ [102/354]   42.0s  seq=DLSANRSVLELSGPAAPL  words= 440
  ✅ [103/354]   42.9s  seq=TGVPPRYIVNVKMRQKTA  words= 465
  ✅ [104/354]   39.6s  seq=LADVDTVINNQLHVDNFN  words= 455
  ✅ [105/354]   41.1s  seq=MQPWQEQCFRFGLKHEMT  words= 464
  ✅ [106/354]   41.7s  seq=VFDVTDQDAVIDGVAAIE  words= 468
  ✅ [107/354]   39.3s  seq=KKLSDSERQQIERYYFDM  words= 431
  ✅ [108/354]   41.1s  seq=SLGSFAILSSILYAKELG  words= 455
  ✅ [109/354]   41.1s  seq=RSANALAAVEKAELLDIV  words= 487
  ✅ [110/354]   41.1s  seq=GSGIVAAGGGSGAATFSV  words= 489
  ✅ [111/354]   41.2s  seq=LTNINNDMFRLRLIVVVL  words= 453
  ✅ [112/354]   40.2s  seq=LFEVLNGEVEMLIPMIDH  words= 459
  ✅ [113/354]   41.3s  seq=RGLLLSALSYLGFETYQV  words= 459
  ✅ [114/354]   39.4s  seq=RIQEEMSRSVVLEDLIPL  words= 437
  ✅ [115/354]   41.6s  seq=GIHKATNVLSFSYEKLSP  words= 463
  ✅ [116/354]   41.0s  seq=EKFRKSAEHCDCLQCFFI  words= 426
  ✅ [117/354]   40.4s  seq=LFSLLFKQFPDTRNYFTH  words= 432
  ✅ [118/354]   36.0s  seq=NQPMFTDHGTFII       words= 401
  ✅ [119/354]   40.9s  seq=LTDHIIPFWNKLRDDENG  words= 473
  ✅ [120/354]   37.8s  seq=TYMPVEEGEYIVNISYAD  words= 407
  ✅ [121/354]   41.3s  seq=HYFLEPIRWMQPELELGN  words= 462
  ✅ [122/354]   41.0s  seq=KISTAEKTMLAKTIMEAD  words= 477
  ✅ [123/354]   38.4s  seq=KSGRTALMLACEIGSSNA  words= 410
  ✅ [124/354]   35.7s  seq=HTMLGSPEQPGVIPRALM  words= 420
  ✅ [125/354]   39.8s  seq=QIYVSGGFNGDMILASVE  words= 449
  ✅ [126/354]   40.5s  seq=GKAGGKDITDIGSLRDSV  words= 437
  ✅ [127/354]   40.2s  seq=SAEEPATLSETNGKSTG   words= 446
  ✅ [128/354]   41.3s  seq=DSMGAVKLAKLLIDKMKC  words= 448
  ✅ [129/354]   41.7s  seq=SSIYPEAKARLPLEALLG  words= 479
  ✅ [130/354]   40.6s  seq=EEVERLRAERDAALADRE  words= 436
  ✅ [131/354]   40.6s  seq=ISNIHNICAPLSPSIQSI  words= 429
  ✅ [132/354]   41.6s  seq=LDVSLAVAWAFMGQIFRE  words= 463
  ✅ [133/354]   41.4s  seq=GATRTLQVLVDLPDGTEA  words= 446
  ✅ [134/354]   41.5s  seq=LDAFNQMVDEV         words= 479
  ✅ [135/354]   39.6s  seq=VTQPLAPVHNPISV      words= 456
  ✅ [136/354]   41.6s  seq=RLFHLIPDGEITSIKINR  words= 476
  ✅ [137/354]   39.5s  seq=ALEANLKLVQQNVRDEDD  words= 439
  ✅ [138/354]   39.2s  seq=LLDVVQFLPEDIIIQTF   words= 441
  ✅ [139/354]   37.9s  seq=HTPGCVTFVLNDHSMAFT  words= 425
  ✅ [140/354]   44.1s  seq=SDCLQTITPTSVVTV     words= 462
  ✅ [141/354]   42.0s  seq=CTLGSEWIQEAGVLLNLT  words= 429
  ✅ [142/354]   43.0s  seq=MMIPDCHKRLE         words= 461
  ✅ [143/354]   42.0s  seq=DADHFTRTANRRDF      words= 424
  ✅ [144/354]   38.8s  seq=SEKRLRAVDPDLVSF     words= 406
  ✅ [145/354]   42.5s  seq=FGVQVPKGPHEESNYEA   words= 455
  ✅ [146/354]   42.2s  seq=ADILQSVQVITDQGLETW  words= 473
  ✅ [147/354]   41.9s  seq=LGLKLGDRILLDAEKAGT  words= 477
  ✅ [148/354]   42.2s  seq=AVLAFSEHHDSALHSYFL  words= 461
  ✅ [149/354]   41.0s  seq=VVFDNMLSPSQQREWERL  words= 462
  ✅ [150/354]   38.7s  seq=LRDGRRAASSSWPGRGSS  words= 404
  ✅ [151/354]   42.1s  seq=RKSTPYGRDTQKVGDICA  words= 445
  ✅ [152/354]   41.9s  seq=ERCFTQQEQQLCN       words= 429
  ✅ [153/354]   41.7s  seq=SDKHLQSWYCRQLRSALL  words= 455
  ✅ [154/354]   41.8s  seq=KGGSGVIHTISHEVIYNS  words= 459
  ✅ [155/354]   36.3s  seq=KHRKSAQDIKKSKIFTKI  words= 398
  ✅ [156/354]   42.0s  seq=PSQQSLENFENTKKYSNE  words= 452
  ✅ [157/354]   41.0s  seq=EFLQYIDINKIPLWLRSS  words= 453
  ✅ [158/354]   42.7s  seq=QKYKEEKQLQKLKEQREK  words= 464
  ✅ [159/354]   42.7s  seq=NYLINKFPNFKIELGMR   words= 467
  ✅ [160/354]   41.7s  seq=NLDALWDCLTGWVDLPLT  words= 464
  ✅ [161/354]   40.2s  seq=GMSGEISDMQYL        words= 460
  ✅ [162/354]   40.6s  seq=METLKSKTKTRVLPSWMT  words= 442
  ✅ [163/354]   39.0s  seq=ATISSPDAVAAAAYTPYF  words= 425
  ✅ [164/354]   39.3s  seq=CPIMDPAWESPEGVPIEG  words= 440
  ✅ [165/354]   40.4s  seq=PKQPSRSSRSSLAATSGI  words= 440
  ✅ [166/354]   41.9s  seq=NIQAPYSNVPALAERWQR  words= 447
  ✅ [167/354]   42.8s  seq=FYVINRIGLENPGIHAFV  words= 486
  ✅ [168/354]   41.4s  seq=EPQIEEVQSEPVCPVPDM  words= 438
  ✅ [169/354]   41.4s  seq=KTVRMQEHLAKREQLDFM  words= 459
  ✅ [170/354]   41.9s  seq=DYPHYTRPAEFRGYVVPQ  words= 435
  ✅ [171/354]   38.3s  seq=EATTQSRAGREEE       words= 415
  ✅ [172/354]   41.2s  seq=FDPGTQPVAGLAAQGFHR  words= 440
  ✅ [173/354]   41.8s  seq=RDMAHEPGNGWTPKHFSR  words= 463
  ✅ [174/354]   40.5s  seq=EHSLPTEIELSEIRKSYN  words= 441
  ✅ [175/354]   40.0s  seq=DLGLAQPNPNVLTI      words= 448
  ✅ [176/354]   43.0s  seq=EGTWQHGYGVSSAYSNYH  words= 456
  ✅ [177/354]   40.0s  seq=LEELEIEKVLIAEEIKMI  words= 448
  ✅ [178/354]   41.3s  seq=FIFLSEKEIHLK        words= 436
  ✅ [179/354]   41.7s  seq=LGGNEPRLVSAAVEQLNT  words= 479
  ✅ [180/354]   42.2s  seq=IKEILKGNTQDISRMLVE  words= 479
  ✅ [181/354]   42.2s  seq=ELTEFKPASEVQEPNEVK  words= 458
  ✅ [182/354]   42.4s  seq=DVIYMMWHAAALGLPFLP  words= 488
  ✅ [183/354]   42.5s  seq=KITITECIYCGKDNKEVE  words= 463
  ✅ [184/354]   42.5s  seq=EPHWSQFDRLLLIKGPKW  words= 470
  ✅ [185/354]   38.7s  seq=SSLSPILMDSFGDDLQKL  words= 427
  ✅ [186/354]   41.8s  seq=WHNFGADYDTTLMAWYER  words= 472
  ✅ [187/354]   42.1s  seq=VTKELKDMTVALVTAAGV  words= 410
  ✅ [188/354]   42.5s  seq=LIRLSLDERIYVKLRSDR  words= 474
  ✅ [189/354]   43.4s  seq=AEEEVPLDPSSSIVE     words= 478
  ✅ [190/354]   42.9s  seq=NLAKLSQNSLAAQEEG    words= 441
  ✅ [191/354]   42.5s  seq=DLLKIFVGGTTADFSAF   words= 444
  ✅ [192/354]   42.1s  seq=TTVAVKKLAAMVDITTEE  words= 441
  ✅ [193/354]   43.3s  seq=IALISMEIMELAREGNKS  words= 458
  ✅ [194/354]   42.7s  seq=SGLRELGEQPLGERIFG   words= 453
  ✅ [195/354]   41.8s  seq=KNLHGTFPFGAGRDGTGE  words= 441
  ✅ [196/354]   42.5s  seq=VKTYKVVEDPTTDGVISW  words= 421
  ✅ [197/354]   41.7s  seq=CNEEFDSIPRRTGAEVDI  words= 461
  ✅ [198/354]   42.8s  seq=PENTILANSFSKTFAMTG  words= 469
  ✅ [199/354]   43.4s  seq=KVYDRCEFARILKKSGMD  words= 462
  ✅ [200/354]   42.3s  seq=AREHHRFGGADHPRADQY  words= 451
  ✅ [201/354]   41.5s  seq=SHVLKDEAGRVLCPILRD  words= 436
  ✅ [202/354]   42.8s  seq=THTGYFTRNSALKTKVEK  words= 463
  ✅ [203/354]   42.6s  seq=FSHIEWNLHLRSNKSIVV  words= 445
  ✅ [204/354]   42.0s  seq=ATLTAARSITKGKIIGII  words= 450
  ✅ [205/354]   42.4s  seq=FTGLSTMADAVLIPERPA  words= 444
  ✅ [206/354]   42.3s  seq=LQREMQNNNDTAVSKGDS  words= 445
  ✅ [207/354]   41.8s  seq=KQIEDLLEPFVYEYIASK  words= 461
  ✅ [208/354]   41.9s  seq=MDSFQKIEKIGEGTYGVV  words= 452
  ✅ [209/354]   41.9s  seq=PGCSKTHLPGFVEQADAL  words= 451
  ✅ [210/354]   42.8s  seq=SKGAQGTAFIVELAYCGL  words= 459
  ✅ [211/354]   42.1s  seq=NAKAVNLWNVAFA       words= 447
  ✅ [212/354]   42.5s  seq=ISLEICAIFHDN        words= 439
  ✅ [213/354]   36.6s  seq=QQLEEKQQHNQRLTQELS  words= 398
  ✅ [214/354]   41.8s  seq=AMGRTNDAVLYGGDVHLF  words= 467
  ✅ [215/354]   42.2s  seq=AAGKKPLDVVLPQLHEAM  words= 422
  ✅ [216/354]   41.2s  seq=APLRIECYDISHLQGDDV  words= 460
  ✅ [217/354]   41.9s  seq=QLARETSVDPDMRKG     words= 442
  ✅ [218/354]   40.3s  seq=RPDLLIDGPLQYDAASVE  words= 435
  ✅ [219/354]   39.2s  seq=LFLRQSVQNPASSFTFN   words= 424
  ✅ [220/354]   42.2s  seq=VWKAALDAGAYGAFVSGS  words= 457
  ✅ [221/354]   39.8s  seq=VLTRLCVALASLALSMMP  words= 432
  ✅ [222/354]   42.0s  seq=DVEWFKSIPLFTKSGRSG  words= 437
  ✅ [223/354]   41.8s  seq=EDVQGFPEKCEDVADILN  words= 464
  ✅ [224/354]   42.2s  seq=SAPVPKVMMPSPASSMFR  words= 464
  ✅ [225/354]   41.8s  seq=GVTHADCQTVSDKVGEIL  words= 450
  ✅ [226/354]   41.1s  seq=TQGVHLWDLQDRVLVRKY  words= 417
  ✅ [227/354]   42.1s  seq=LEDFLLNLGRKHQAVGVN  words= 469
  ✅ [228/354]   41.9s  seq=TGAPGGNFRTWTPTPPER  words= 452
  ✅ [229/354]   41.8s  seq=QDNNFCNPSKPVSLESLE  words= 465
  ✅ [230/354]   39.4s  seq=REGTAEDMLQQPMLFFGA  words= 420
  ✅ [231/354]   42.7s  seq=ASDDANDSPTIEYNIKQF  words= 443
  ✅ [232/354]   42.2s  seq=HAEHKVKIGVEQKYGQFP  words= 482
  ✅ [233/354]   42.2s  seq=DLQAAPPNSYVSFSDDDF  words= 479
  ✅ [234/354]   42.0s  seq=SSNFSKRPYVL         words= 440
  ✅ [235/354]   42.0s  seq=PQVPPGKYIVRADVS     words= 449
  ✅ [236/354]   42.4s  seq=QVNPSKRLDHLQR       words= 466
  ✅ [237/354]   37.9s  seq=LKNVVFAADLSNA       words= 384
  ✅ [238/354]   42.1s  seq=VFKPKKVLPPPPTTKSKG  words= 444
  ✅ [239/354]   42.3s  seq=MLRDVMLRLRQVCNEYDC  words= 471
  ✅ [240/354]   41.7s  seq=PISNPVARAHVR        words= 452
  ✅ [241/354]   42.3s  seq=ATTQSSVSRWLRKIQAVK  words= 439
  ✅ [242/354]   40.3s  seq=YLHHGLVIWLDGS       words= 431
  ✅ [243/354]   43.1s  seq=GGWLDIVKAIVVPAARET  words= 442
  ✅ [244/354]   40.9s  seq=RIRIALGNEAS         words= 463
  ✅ [245/354]   41.8s  seq=EQSNETGLEAQENDKNDE  words= 449
  ✅ [246/354]   40.3s  seq=TVEEEALLSGEVCLRRKV  words= 438
  ✅ [247/354]   41.8s  seq=KIAAFQQMFQNQQLQPEH  words= 455
  ✅ [248/354]   39.2s  seq=ITPATPFTPAIITEITAA  words= 442
  ✅ [249/354]   38.1s  seq=DNSSAQVDIPL         words= 425
  ✅ [250/354]   42.1s  seq=NILNTTATQNTEEHQRYG  words= 461
  ✅ [251/354]   40.1s  seq=IKSVMLTQEQIQARIAEL  words= 420
  ✅ [252/354]   40.7s  seq=DSHEERHHGRHGHHKYGR  words= 451
  ✅ [253/354]   42.2s  seq=KRLDAQASTASASPAKAK  words= 461
  ✅ [254/354]   41.5s  seq=NPEMTQIRGILSQRRLIK  words= 436
  ✅ [255/354]   42.6s  seq=NVALLNAMYYYHKLSTIC  words= 434
  ✅ [256/354]   41.7s  seq=IPDKDLDISTSRAG      words= 473
  ✅ [257/354]   42.3s  seq=KSIEKEFNYNHIIKFSSI  words= 463
  ✅ [258/354]   42.3s  seq=QQLNAASMWGNLTGLNSL  words= 459
  ✅ [259/354]   41.8s  seq=QRPDATGHFSRRWAAKQA  words= 439
  ✅ [260/354]   41.9s  seq=DSPAHHAETLSTVQLA    words= 435
  ✅ [261/354]   39.8s  seq=LFETDNAADVKDLIRAPG  words= 436
  ✅ [262/354]   42.4s  seq=HVDNDRWKGVPFVFVSGK  words= 434
  ✅ [263/354]   38.5s  seq=PQLCNQKFELKLNDVRFV  words= 417
  ✅ [264/354]   42.6s  seq=PSEIKKLRTESILKELIP  words= 455
  ✅ [265/354]   41.2s  seq=KRFHSVGSLIQRHQQMIR  words= 445
  ✅ [266/354]   42.3s  seq=QQQGRLPLAAKDNNRSKS  words= 450
  ✅ [267/354]   37.3s  seq=FAHEIVIVNIDN        words= 404
  ✅ [268/354]   38.7s  seq=DVQFLSYKEKTNEIFFTI  words= 426
  ✅ [269/354]   39.5s  seq=AISLFAAEAKGISSPVSG  words= 437
  ✅ [270/354]   41.1s  seq=AASKLKTGKSPLSIVTDK  words= 437
  ✅ [271/354]   39.9s  seq=PAQIRKHMQEKIADRISK  words= 442
  ✅ [272/354]   42.9s  seq=KKVWFIFHVCPKLKQRIL  words= 467
  ✅ [273/354]   42.5s  seq=IELNKIKTIYSHPQPFQQ  words= 480
  ✅ [274/354]   42.3s  seq=GAQKTSIACIEDGISQLD  words= 491
  ✅ [275/354]   42.5s  seq=ERYILQTINGFKPAVVKG  words= 435
  ✅ [276/354]   42.4s  seq=MKETGSECVIHTHSKCAN  words= 442
  ✅ [277/354]   39.2s  seq=ETLIQTIESVRNVEGVLA  words= 432
  ✅ [278/354]   41.2s  seq=MMIEIIEPNWHIFIEKMK  words= 446
  ✅ [279/354]   41.6s  seq=MTTDFDLSLDNSPLLQSI  words= 454
  ✅ [280/354]   41.6s  seq=TAVTAIADVVQMNEPALL  words= 476
  ✅ [281/354]   42.4s  seq=AEIGRGSYGVVYEAVAGR  words= 472
  ✅ [282/354]   42.2s  seq=LVLRNRIRNNQTISNHQ   words= 474
  ✅ [283/354]   42.6s  seq=NISHYSVLFKRLYVLLSV  words= 460
  ✅ [284/354]   37.6s  seq=VKVGINGFGRIGRLVTRA  words= 395
  ✅ [285/354]   40.3s  seq=LPVNSPMNKGDTEVMKCI  words= 395
  ✅ [286/354]   41.5s  seq=EPNPDEFFGLM         words= 454
  ✅ [287/354]   42.3s  seq=YVNLNHIMPTRYSVKELC  words= 483
  ✅ [288/354]   42.2s  seq=RAGGIPVVDWHTLSPRDA  words= 455
  ✅ [289/354]   42.6s  seq=IPDGMCIDVEGKLWVACY  words= 449
  ✅ [290/354]   39.7s  seq=LRSLEAVERALSLCQYAV  words= 433
  ✅ [291/354]   42.3s  seq=VHEEAFDDFLRYKTRIPV  words= 458
  ✅ [292/354]   39.9s  seq=ALSILRGLEKLAKMGIAL  words= 408
  ✅ [293/354]   38.1s  seq=GVNVNGDSLPVAINGPVK  words= 420
  ✅ [294/354]   42.2s  seq=ILKSYYSRFDRIMWIDTL  words= 451
  ✅ [295/354]   42.4s  seq=HPLMRKWWNHMSDIMETN  words= 431
  ✅ [296/354]   42.6s  seq=QSMKNVEEQLIIMRSKTT  words= 421
  ✅ [297/354]   42.4s  seq=LVESASVVVLGGGVIGLE  words= 461
  ✅ [298/354]   42.5s  seq=FDGNGFRSKVNTPAIDD   words= 434
  ✅ [299/354]   43.1s  seq=SLMPLHRKISTTEDSGIT  words= 479
  ✅ [300/354]   41.8s  seq=IVQAGKNAANPHLGPTMN  words= 447
  ✅ [301/354]   41.6s  seq=HPKARIYAEAGPIIIGEG  words= 459
  ✅ [302/354]   42.2s  seq=FFSRPDLVYVPYGERAWG  words= 434
  ✅ [303/354]   39.4s  seq=ELAPVAIKAGEILARRLF  words= 410
  ✅ [304/354]   42.6s  seq=KRFWQLVPLAIKIYRAWK  words= 456
  ✅ [305/354]   41.8s  seq=TVLGAPPNPTSSHSAVLV  words= 456
  ✅ [306/354]   42.0s  seq=LAHTYQSPLLYCDLEVEG  words= 479
  ✅ [307/354]   42.8s  seq=IKSYVQGFEMLLNQTINI  words= 429
  ✅ [308/354]   42.6s  seq=RSDNSPLPERKLVTLIQE  words= 452
  ✅ [309/354]   40.5s  seq=EQYCDIPLGLYVIRGENV  words= 451
  ✅ [310/354]   41.8s  seq=LIVLDDIDNKDHY       words= 458
  ✅ [311/354]   42.6s  seq=IAETSEIDRATITPESHT  words= 455
  ✅ [312/354]   41.8s  seq=DLSSSLHSDSSYPPDAGL  words= 453
  ✅ [313/354]   42.1s  seq=DYLLNINPDFEHGEIRVG  words= 457
  ✅ [314/354]   42.9s  seq=YTQPNSLWRGPDEDDLDS  words= 443
  ✅ [315/354]   39.4s  seq=ANCSVEEAVSLGASAVGY  words= 434
  ✅ [316/354]   42.3s  seq=KMHAFTEVRNINTYDEIW  words= 477
  ✅ [317/354]   41.8s  seq=KGPNRIKQALKNKE      words= 450
  ✅ [318/354]   40.4s  seq=FETETDATAVDC        words= 462
  ✅ [319/354]   37.2s  seq=VVKCSYRLGSPDSQCN    words= 387
  ✅ [320/354]   41.4s  seq=ENDTSIDYSVVP        words= 457
  ✅ [321/354]   42.8s  seq=SVQALLFMVLPHLHTLVN  words= 391
  ✅ [322/354]   34.9s  seq=GGGEGHQPAANNNNNNHN  words= 367
  ✅ [323/354]   42.2s  seq=IFPDPSNFDCYCKLKDRL  words= 470
  ✅ [324/354]   42.0s  seq=LDIITNKVSAQEQRIC    words= 439
  ✅ [325/354]   36.7s  seq=LQWIDPGKTITFLGSSGA  words= 400
  ✅ [326/354]   41.2s  seq=RYILRFPALETLMLDDNR  words= 435
  ✅ [327/354]   38.8s  seq=PITYLDAILAAVRLLNQR  words= 393
  ✅ [328/354]   39.1s  seq=KRRGSVTTRYQFLMIHLL  words= 427
  ✅ [329/354]   40.8s  seq=CTRFISKEILTIREAVWL  words= 447
  ✅ [330/354]   42.4s  seq=TPYLPAGLRVRTPALPGH  words= 486
  ✅ [331/354]   42.0s  seq=NAPIVVGRGGAGNIFFNK  words= 481
  ✅ [332/354]   42.7s  seq=ENFGNEFISTLLNKKTQD  words= 451
  ✅ [333/354]   40.2s  seq=RMFSKKNDHYDCYIDIQS  words= 439
  ✅ [334/354]   40.9s  seq=SPRLMLAMYSCDVQATSE  words= 455
  ✅ [335/354]   40.5s  seq=DHFLPTFNAEPLQDDKVS  words= 427
  ✅ [336/354]   38.5s  seq=KAANQRAVQMLEKCGTTQ  words= 405
  ✅ [337/354]   40.9s  seq=IKHYYDENPDIPPEILLS  words= 439
  ✅ [338/354]   42.6s  seq=QTRLKRTPRLRFEPDPTV  words= 474
  ✅ [339/354]   41.2s  seq=GSASPASGAATP        words= 448
  ✅ [340/354]   42.0s  seq=RPSMVEIWSFSDFLSIAP  words= 482
  ✅ [341/354]   41.5s  seq=EPNPDEFVGLM         words= 456
  ✅ [342/354]   42.1s  seq=QNVMGRGIALPGMANPQM  words= 468

In [ ]:
def fmt(pipe_str, max_items=8):
    items = [x.strip() for x in str(pipe_str).split('|') if x.strip()][:max_items]
    return ', '.join(items)

rows = []
for idx, (seq, data) in enumerate(retrieval_results.items()):
    explanation = explanations.get(seq, '[No explanation generated]')
    props = compute_properties(seq)
    row = {
        'seq_idx':           idx + 1,
        'query_sequence':    seq,
        'query_length':      props['length'],
        'prob_amp':          round(data['prob_amp'], 6),
        'true_label':        data['true_label'],
        'prediction_result': data['result'],
        'in_starpep':        any(h.get('is_self_match', False) for h in data['hits']),
        'hydrophobicity_pct':props['hydrophobicity'],
        'net_charge':        props['net_charge'],
        'pos_charge_pct':    props['pos_charged_pct'],
        'neg_charge_pct':    props['neg_charged_pct'],
    }
    for n in range(1, TOP_K + 1):
        p = f'hit{n}_'
        if n <= len(data['hits']):
            h = data['hits'][n - 1]
            row[p+'starpep_id']    = h['id']
            row[p+'is_self_match'] = h.get('is_self_match', False)
            row[p+'cosine_sim']   = round(h['cosine_sim'], 4)
            row[p+'sequence']      = h['sequence']
            row[p+'length']        = h.get('length', len(h['sequence']))
            row[p+'activities']    = fmt(h.get('relatedTo',       ''))
            row[p+'targets']       = fmt(h.get('assessedAgainst', ''), max_items=10)
            row[p+'source']        = fmt(h.get('producedBy',      ''), max_items=4)
            row[p+'modifications'] = fmt(h.get('modifiedBy',      ''), max_items=4)
        else:
            for col in ['starpep_id','cosine_sim','sequence','length',
                        'activities','targets','source','modifications']:
                row[p+col] = ''
    row['biological_explanation'] = explanation
    rows.append(row)

results_df = pd.DataFrame(rows)
results_df.to_csv(OUTPUT_CSV, index=False, encoding='utf-8')

print(f'Results saved -> {OUTPUT_CSV}')
print(f'   Rows    : {len(results_df)}')
print(f'   Columns : {len(results_df.columns)}')
print(f'   Size    : {OUTPUT_CSV.stat().st_size / 1024:.1f} KB')
print()
print('Column layout:')
print('  [query]           seq_idx  query_sequence  query_length  prob_amp  true_label  prediction_result')
print('  [physicochemical] hydrophobicity_pct  net_charge  pos_charge_pct  neg_charge_pct')
for n in range(1, TOP_K + 1):
    print(f'  [hit {n}]           hit{n}_starpep_id  hit{n}_cosine_sim  hit{n}_sequence  hit{n}_length')
    print(f'                    hit{n}_activities  hit{n}_targets  hit{n}_source  hit{n}_modifications')
print('  [explanation]     biological_explanation')
print()
display(results_df[['query_sequence','prob_amp','prediction_result',
                     'hit1_starpep_id','hit1_cosine_sim','hit1_activities']].head(3))

Results saved -> /Users/deepugeorgejacob/Projects/amp-rag/results/non_amp_rag_results.csv
   Rows    : 354
   Columns : 39
   Size    : 1389.3 KB

Column layout:
  [query]           seq_idx  query_sequence  query_length  prob_amp  true_label  prediction_result
  [physicochemical] hydrophobicity_pct  net_charge  pos_charge_pct  neg_charge_pct
  [hit 1]           hit1_starpep_id  hit1_cosine_sim  hit1_sequence  hit1_length
                    hit1_activities  hit1_targets  hit1_source  hit1_modifications
  [hit 2]           hit2_starpep_id  hit2_cosine_sim  hit2_sequence  hit2_length
                    hit2_activities  hit2_targets  hit2_source  hit2_modifications
  [hit 3]           hit3_starpep_id  hit3_cosine_sim  hit3_sequence  hit3_length
                    hit3_activities  hit3_targets  hit3_source  hit3_modifications
  [explanation]     biological_explanation

,query_sequence,prob_amp,prediction_result,hit1_starpep_id,hit1_cosine_sim,hit1_activities
0,VVRVGGRVPVLAGTGLSGTAKT,0.276276,TN,starPep_04826,0.9573,"Anti-Gram negative, Toxic to mammals, Anti-Gra..."
1,LEPGVVIGYDR,0.270477,TN,starPep_04432,0.9686,"Anti-Gram positive, Anti-Gram negative, Toxic ..."
2,FEDAALIPSGQKAAFLKATDTLLSAVTECWRTDFATLRLHGDCHAG...,0.297874,TN,starPep_02624,0.8439,"Anti-Gram negative, Anti-Gram positive, Antimi..."

In [ ]:
row = results_df.iloc[0]
print('=' * 80)
print(f"  seq_idx            : {row['seq_idx']}")
print(f"  query_sequence     : {row['query_sequence']}")
print(f"  prob_amp           : {row['prob_amp']:.4f}")
print(f"  prediction_result  : {row['prediction_result']}")
print(f"  net_charge         : {row['net_charge']:+d}")
print(f"  hydrophobicity_pct : {row['hydrophobicity_pct']}%")
print()
for n in range(1, TOP_K + 1):
    p = f'hit{n}_'
    print(f"  Hit #{n}: {row[p+'starpep_id']}  cosine_sim={row[p+'cosine_sim']:.2f}")
    print(f"    Sequence   : {row[p+'sequence']}")
    print(f"    Activities : {str(row[p+'activities'])[:80]}")
    print(f"    Targets    : {str(row[p+'targets'])[:80]}")
    print()
print('-' * 80)
print('  BIOLOGICAL EXPLANATION (Mistral-7B-Instruct, T=0):')
print('-' * 80)
print(row['biological_explanation'])
print('=' * 80)

================================================================================
  seq_idx            : 1
  query_sequence     : VVRVGGRVPVLAGTGLSGTAKT
  prob_amp           : 0.2763
  prediction_result  : TN
  net_charge         : +3
  hydrophobicity_pct : 40.9%

  Hit #1: starPep_04826  cosine_sim=0.96
    Sequence   : VGVGGGFGR
    Activities : Anti-Gram negative, Toxic to mammals, Anti-Gram positive, Antibacterial
    Targets    : Vibrio cholerae, Pseudomonas aeruginosa, Staphylococcus aureus, Human erythrocyt

  Hit #2: starPep_02065  cosine_sim=0.96
    Sequence   : AKAWGIPPHVIPQIVPVRIRPLCGNV
    Activities : Antifungal, Anti-Gram positive, Antioxidant, Antimicrobial, Antibacterial, Anti-
    Targets    : Escherichia coli, Candida albicans, Bacillus subtilis, Staphylococcus aureus

  Hit #3: starPep_07912  cosine_sim=0.95
    Sequence   : VSGPAGPPGTH
    Activities : Antifungal, Anti-Gram positive
    Targets    : Aspergillus niger, Listeria monocytogenes, Bacillus cereus

--------------------------------------------------------------------------------
  BIOLOGICAL EXPLANATION (Mistral-7B-Instruct, T=0):
--------------------------------------------------------------------------------
1. MISSING AMP FEATURES: The query sequence VVRVGGRVPVLAGTGLSGTAKT lacks several key physicochemical properties that are hallmarks of antimicrobial peptides (AMPs).
   - Length: AMPs typically range from 12 to 50 amino acids, while the query sequence is relatively long at 22 residues. Shorter sequences may be more effective due to their ability to interact with multiple membrane targets.
   - Amphipathicity: AMPs often exhibit an amphipathic nature, meaning they have both hydrophilic and hydrophobic regions that can interact with the microbial membrane. The query sequence has a high proportion of hydrophobic residues (40.9%), but it lacks sufficient hydrophilic residues to balance this hydrophobicity, which is crucial for effective interaction with microbial membranes.
   - Charge: AMPs often have a net positive charge that helps them bind to negatively charged microbial membranes. The query sequence has a net charge of +3, but it lacks any negatively charged residues, which could limit its ability to interact with microbial membranes.

2. CONTRAST WITH AMP NEIGHBOURS: The query sequence differs significantly from its closest retrieved AMP neighbours in terms of length, amphipathicity, and charge distribution. For example, the most similar AMP (starPep_04826) is only 9 residues long, while the query sequence is 22 residues long. Additionally, starPep_04826 has a net charge of +1, which may contribute to its antimicrobial activity by allowing it to interact with negatively charged microbial membranes.

3. STRUCTURAL DEFICIENCIES: The query sequence does not appear to have any known structural motifs commonly found in AMPs such as alpha-helices or beta-sheets. This lack of a defined structure may limit its ability to interact effectively with microbial membranes.

4. PHYSICOCHEMICAL BARRIERS: The high proportion of hydrophobic residues and the absence of negatively charged residues in the query sequence could prevent effective interaction with microbial membranes compared to canonical AMPs. Canonical AMPs often have a balance between hydrophilic and hydrophobic residues, which allows them to insert into the lipid bilayer of the microbial membrane and disrupt its integrity.

5. POTENTIAL ALTERNATIVE FUNCTION: Without additional information about the biological context in which this sequence was found, it is difficult to definitively determine an alternative function. However, given its length and hydrophobicity, it could potentially serve as a structural protein or participate in cell adhesion.

6. MODIFICATIONS FOR AMP ACTIVITY: To confer antimicrobial activity to the query sequence, several amino acid substitutions or modifications could be considered. For example, introducing negatively charged residues (such as glutamic acid or aspartic acid) could help balance the hydrophobicity and allow for interaction with microbial membranes. Additionally, shortening the sequence to a more typical AMP length (12-50 residues) might also improve its antimicrobial potential by increasing its ability to interact with multiple membrane targets. However, these modifications would need to be tested experimentally to determine their effects on antimicrobial activity.
================================================================================